SDFIdk/FIRE

.circleci/config.yml
README.md
docker-compose.sh
docker-compose.yml
misc/dbsetup.sh
misc/debian/setup.sh
misc/oracle/dbsetup.sh
misc/oracle/login.sql
test/fixtures/sql/fikspunkt_forvaltning.sql
test/fixtures/sql/init.sql

Fixes from https://github.com/Septima/fikspunktsregister/pull/11 to get that into master before we try to use new schema version.

Rework with login.sql for sqlplus

---

.circleci/config.yml
misc/oraclelinux/setup.sh

ref https://github.com/Septima/fikspunktsregister/issues/17

Use Miniconda instead of system level Python

---

fireapi/model/__init__.py
fireapi/model/punkttyper.py
fireapi/model/sagstyper.py
test/conftest.py
test/test_punkt.py

Add more models. Expand test skeleton. Make fra/til readonly

add_models

---

fireapi/firedb.py
test/conftest.py
test/test_beregning.py
test/test_firedb.py
test/test_observation.py

By no means finished but might be useful to get this in for @klavspc to be able to use `hent_observationer_naer_punkt`.

Convenience methods part 1

---

fireapi/firedb.py
fireapi/model/__init__.py
test/test_firedb.py

Also includes WIP indset methods.

Implement hent_observationer_naer_*

---

fireapi/firedb.py
test/conftest.py

I missed it too much when testing. 
Implements suggestion from #60

Add debug param to firedb constructor

---

fireapi/firedb.py
test/test_firedb.py

UTF8 support

---

fireapi/firedb.py
test/test_beregning.py

ref https://github.com/Septima/fikspunktsregister/issues/68

Attempt to fix constraints issues on insertion

---

fireapi/firedb.py

ref https://github.com/Septima/fikspunktsregister/issues/68

Disable autoflush and remove redundant flushes

---

fireapi/firedb.py
fireapi/model/sagstyper.py
test/test_beregning.py
test/test_observation.py
test/test_punkt.py

Implement sagseventinfo and accompanying types.
Let user specify sagsevent to "indset_xxx" methods. Otherwise sagseventinfo and accompanying types would have to be filled outside the main transaction

sagseventinfo

---

README.md
environment-dev.yml
environment.yml

Brush up environment.yml and create environment-dev.yml

conda-environment

---

fireapi/firedb.py
test/test_srid.py

Fix firedb.hent_srider with namespace

---

fireapi/firedb.py
test/test_observationtype.py
test/test_punktinformationtype.py
test/test_srid.py

Add indset_*type functions

---

.travis.yml
README.md
docs/api/fireapi.firedb.rst
docs/api/fireapi.model.columntypes.rst
docs/api/fireapi.model.geometry.rst
docs/api/fireapi.model.punkttyper.rst
docs/api/fireapi.model.rst
docs/api/fireapi.model.sagstyper.rst
docs/api/fireapi.rst
docs/api/modules.rst
docs/conf.py
docs/index.rst
environment-dev.yml

- describe how to in readme
- add sphinx as dev dependency
- update api docs
- add @kbevers as author

Improve docs infrastructure

---

.circleci/config.yml
.travis.yml
docs/for_udviklere.rst
docs/installation.rst
environment-dev.yml
environment.yml

Bl.a. indsat QGIS LTR i brugermiljø og for konsistens også i udviklermiljø, så "vi er på samme side"

Korrektioner til installationsmiljøfiler og -vejledninger

---

docs/for_udviklere.rst
docs/installation.rst

Formateringsfejl og vejledning til opsætning af lokalt testmiljø.

Opdateringer til dokumentation

---

fire/api/model/geometry.py
test/test_geometri.py

Opstramning på koden i `fire.api.model.geometry` samt et anstændigt dækkende sæt af tests af samme modul.

Geometritests

---

test/sql/testdata.sql

Der var smuttet et par vigtige koordinater i første omgang. Det rådes der bod på nu!

Tilføj manglende koordinater til testdatasæt

---

fire/cli/mtl.py

Et foreløbigt forsøg på type annotering i mtl, må meget gerne checkes om det ser rigtigt ud

Typeannotering

---

fire/cli/info.py

Drop caching af punktinformationstype: Det sker på APIniveau nu (og plads til yderligere review, @kbevers)

Kuppel: Observatorieoverbygning

---

fire/api/firedb.py
fire/api/model/punkttyper.py
fire/cli/info.py
test/test_punkt.py

Fjerner overflødige imports og omdirigerer `kanonisk_ident()` til `Punkt.ident`.

Opfølgning på #151

---

fire/api/firedb.py
fire/cli/info.py

Ident opslagslogik flyttet og modificeret fra fire.cli.info.punkt.
Tilføjer desuden FireDb.hent_punkter() der returnerer alle punkter der
matcher et givent ident. Internt benytter FireDb.hent_punkt() denne
funktion og returnerer første forekomst fra hent_punkter().

Flyt ident opslagslogik fra fire info punkt til hent_punkt

---

sql/ddl.sql

Løser problemer fundet under review af #164

Ret stavefejl i DDL

---

fire/cli/info.py
test/info/test_info.py

Giver liste af mulige SRID. ved at skrive --alle fås også TS 
Closes #153

Srid liste

---

.circleci/config.yml
fire/cli/info.py
sql/ddl.sql
test/info/test_info.py
test/test_observationtype.py

Den har vi manglet...
Eksempel:
```
--- OBSERVATIONSTYPE ---
Navn        :  retning
Beskrivelse :  Horisontal retning med uret fra opstilling til sigtepunkt (reduceret til ellipsoiden)
Værdi1      :  Retning [m]
Værdi2      :  Varians  retning hidrørende instrument, pr. sats  [rad^2]
Værdi3      :  Samlet centreringsvarians for instrument prisme [m^2]
Sigtepunkt? :  True
```

Tilføj `fire info obstype` kommando

---

fire/cli/mtl.py
test/mtl/test_mtl.py

MTL-funktionaliteten er nu mindre black-boxagtig. Den er inddelt i et indlæsnings- og et beregningstrin. Testen er stadig rudimentær, men lægger op til mere udførlig testning ifbm udvikling af resultatilægningsfunktionalitet

MTL refaktor

---

fire/cli/info.py

Da vi indførte mindre pedantiskhed mht. foranstillede nuller i landsnumre, glemte vi købstadsnumrene. Det er rettet her.
Desuden er indført større forståelse for minuskler og udeladte punktummer i GI/GM-numre og GNSS-id'er

info punkt: Vær mindre pedantisk i flere tilfælde

---

fire/cli/mtl.py

En del steder i MTL anvendtes nøgne `print`-instruktioner. Disse er nu ændret til `fire.cli.print`. Desuden er en hel del tilfælde af strengkonstruktioner, ifbm. `print`, `open` o.l., rettet fra at benytte formen `navn + ".xlsx"` til `f"{navn}.xlsx"`

MTL: Konsekvent anvendelse af f-strenge og fire.cli.print

---

sql/ddl.sql

Småændringer i eventtypebeskrivelser efter review af #164

Forbedr eventtypebeskrivelser

---

fire/cli/info.py

Man kan nu:
- Skrive med store og små bogstaver som man har lyst til
- Få vist en liste med alle tilgængelige punktinfotyper
- Få vist en liste med alle punktinfotyper der matcher `infotype`-søgeordet - hvis der kun findes et match vises al tilgængelig information.
Eksempler på tilføjelserne til brugerinterfacet:
```
$ fire info infotype
Følgende punktinfotyper er tilgængelige:
ATTR:TEST
ATTR:tabtgået
ATTR:test
IDENT:GNSS
IDENT:landsnr
NET:TEST
$ fire info infotype ident
"ident" matcher følgende punktinfotyper:
IDENT:GNSS
IDENT:landsnr
$ fire info infotype attr:tabtgået
--- PUNKTINFOTYPE ---
Name        :  ATTR:tabtgået
Description :  Fysisk punkt ikke længere tilgængeligt
Type        :  PunktInformationTypeAnvendelse.FLAG
```
Closes #176

Forbedr søgning efter punktinfotype med `fire info infotype`:

---

docs/datamodel.rst
fire/api/firedb.py
fire/api/gama/writer.py
fire/api/model/__init__.py
fire/api/model/punkttyper.py
fire/api/model/sagstyper.py
fire/cli/info.py
flame/algorithms/import_observationer_by_location.py
sql/ddl.sql
test/conftest.py
test/sql/testdata.sql
test/test_beregning.py
test/test_observation.py
test/test_observationtype.py

... og tilhørende konsekvensrettelser i Pythonkode.
Closes #169

Sprogkorrektioner i DDL

---

fire/api/firedb.py

Indsæt flere punkter i punkttabel, under samme sagsevent

Tilføj API-kald 'indset_flere_punkter'

---

fire/cli/info.py

Undgå fejl ved punkter der ikke har et geometriobjekt

fire info punkt: Håndter manglende geometri på en pæn måde

---

fire/api/firedb.py
fire/api/model/__init__.py
fire/api/model/columntypes.py
fire/api/model/geometry.py
fire/cli/__init__.py
fire/cli/gama.py
fire/cli/info.py
fire/cli/main.py
fire/cli/utils.py
misc/oracle/login.sql
test/gama/test_gama_cli_read.py

Der skal nok være noget jeg har overset, men de fleste engelske fejlmeldinger og docstrings skulle gerne være oversat nu.
Closes #187

Oversæt fejlmeddelelser og docstrings til dansk

---

fire/api/firedb.py
fire/api/model/columntypes.py
fire/api/model/sagstyper.py
scripts/init-db.sh

- Nøjes med en slags heltalsenumereringsklasse
- Udryd henvisninger til observationstypenamespaces
- Tilføj script til at initialisere lokal database med Docker

Diverse smårettelser

---

fire/cli/niv.py

Udtrykket for spredning var forkert (brugte ikke geometrisk sum af spredningskomponenterne). Det er korrigeret her. Samtidig er håndteringen af observationer strammet op, mhp at anvende det ny spredningsudtryk korrekt.

Korriger spredningsudtryk og brug det korrekt i observationshåndteringen

---

fire/cli/niv.py

**Foreløbige koter:** Når foreløbig kote mangler indfører vi et nul med 1 km spredning, observeret i 1800, til brug som foreløbig værdi (denne værdi kommer aldrig i databasen, den er til rent formel brug og erstattes af den nyberegnede kote i det videre arbejde).
**Lokationskoordinater:** Når lokationskoordinater indlæses i regneark kan de enten være i geografiske koordinater, eller i UTM32. Dette afspejles ved at rette de hidtil brugte søjleoverskrifter fra (φ, λ) til (Nord, Øst), som er en tilpas blød mellemvare, til også at kunne fortolkes som (Northing, Easting)

Opstramning af lokations- og foreløbig kote-data

---

fire/cli/niv.py

Viser funktionaliteten af revisionsindlæsningsprogrammet som dry-run, skriver endnu ikke til databasen

"Revision ind" på demoniveau

---

fire/cli/niv.py

Eliminer versalfølsomhed for nivellementsobservationstypebetegnelserne
MGL, MTL og NUL
Introducer og dokumenter håndtering af NUL i spredning()
Ret søjlenavnene "Fix" og "Hold" til "Fasthold" og "Udelad publikation"
Tilføj manglende søjlenavn "Opløft [mm/år]" i punktoversigt
Ret det misvisende funktionsnavn check_om_sag_er_korrekt_oprettet()
til find_sag()

Korriger sproglige uhensigtsmæssigheder

---

fire/cli/niv.py

(er-du-helt-helt-helt-sikker dialogen, bare en smule strammere)

Eliminer overflødige responsvariable

---

sql/ddl.sql

Tilføjes pt. i forbindelse med migrationen. Skal registreres her frem for i FIRE-DDL. Ændringer i FIRE-DDL kommer efterfølgende.

Tilføj diverse index til DDL

---

docs/conf.py
fire/api/firedb.py
fire/api/model/columntypes.py
fire/cli/gama.py
fire/cli/info.py
fire/cli/niv.py
flame/algorithms/import_observationer_by_location.py
test/conftest.py
test/test_beregning.py
test/test_ident.py
test/test_sag.py

Black version 20 gør mere ud af bl.a. funktionshovedformateringen. Lad os få det på banen!

Ny Black, nye ombrydninger

---

fire/cli/niv/__init__.py
fire/cli/niv/ilæg_nye_punkter.py
fire/cli/niv/læs_observationer.py
fire/cli/niv/regn.py

Fremfind et faneblad gennem projektnavn, fanebladsnavn og arkdefinition. Forberedelse til forbedret beregningsarbejdsgang

Generel fanebladsfremfindingsfunktionalitet

---

fire/cli/niv/__init__.py
fire/cli/niv/ilæg_nye_koter.py
fire/cli/niv/ilæg_nye_punkter.py
fire/cli/niv/ilæg_observationer.py
fire/cli/niv/ilæg_revision.py
fire/cli/niv/læs_observationer.py
fire/cli/niv/netoversigt.py
fire/cli/niv/regn.py

Efter to indledende commits, der indfører forberedende funktionalitet, tilpasses beregningsarbejdsgangen, så den matcher gældende og historisk fornuftig praksis:
* Observationsindlæsningen forbereder kontrolberegning 
* Kontrolberegning forbereder endelig beregning
* Endelig beregning forbereder databaseilægning, og dermed endeligt resultat.
Sidstnævnte er en sag for et kommende PR.

Beregningsarbejdsgangsforbedring

---

fire/cli/info.py

Gør det muligt at skelne mellem aktuelle og slukkede punktinformationer

info punkt: marker slukkede punktinformationer

---

fire/api/firedb.py
test/conftest.py

Brug klasseglobal variabel til styring af tabel-præfiks

---

fire/cli/niv/ilæg_revision.py

Udstillingsmodellen er desværre baseret på projicerede koordinater, mens vi i forvaltningssystemet typisk kun registrerer kartesiske- eller geografiske koordinater - i hvert fald for moderne GNSS-baserede systemer,.
For DK og FO er det ikke noget problem, fordi vi kan lade Oracle SDO projicere under overførslen. Men for Grønland har vi det problem at Oracle SDO benytter Snyder's hårdt trunkerede rækkeudvikling af transvers mercator. Den er god nok inden for de formelle utm-zoneintervaller på 6 grader, men falder til jorden når man forsøger at afbilde hele Grønland ind i UTM zone 24. Her er vi nødt til at anvende Poder/Engsager-rækken, som er langt mere numerisk robust.
For at undgå at udstille SDO-mishandlede UTM-koordinater udløser Grønlandske planfikspunkter uden UTM-koordinat, …

niv: ilæg_revision - autogenerer GL plankoordinater

---

fire/cli/niv/regn.py

HTML-fil navngives efter beregningstype

---

fire/cli/niv/ilæg_revision.py

niv: Fjern overflødige asserts

---

fire/api/_firedb_luk.py
test/test_punkt.py

Håndter lukning af punkter uden geometri korrekt

---

environment-dev.yml
environment.yml

Nedgrader gama til 2.09 og xlrd til 1.2.0

---

fire/cli/niv/regn.py

Ret delta og upliftrapportering til mm hhv mm/år

---

fire/api/_firedb_indset.py
fire/api/firedb.py
fire/api/gama/reader.py
fire/cli/niv/ilæg_nye_punkter.py
fire/cli/niv/ilæg_observationer.py
fire/cli/niv/ilæg_revision.py
test/test_beregning.py
test/test_observation.py
test/test_punkt.py
test/test_punktinformation.py

Fjern indset_-funktioner

---

fire/cli/niv/__init__.py
fire/cli/niv/ilæg_nye_koter.py
fire/cli/niv/ilæg_nye_punkter.py
fire/cli/niv/ilæg_observationer.py
fire/cli/niv/ilæg_revision.py
fire/cli/niv/opret_sag.py

Workshop docs skal have en overhaling før denne merges. 
Closes #316

fire niv: Indfør automatisk registrering af sagsbehandler

---

fire/cli/niv/ilæg_observationer.py

fire niv ilæg-observationer: flush, commit, rollback

---

fire/cli/niv/ilæg_nye_koter.py

Opdater fire niv ilæg-nye-koter

---

fire/cli/niv/udtræk_revision.py

Forbedrer fremsøgning af relevanter punkter med en faktor 5-7. Enkelte
overflødige punkter fanges, sandsynligvis fordi herred- og
sognegrænserne der i øjeblikket er indlæst i databasen er forsimplet med
Douglas-Peuckert med henblik på scriptbar indlæsning ved overførsel fra
REFGEO.
Close #334

Optimer fire niv udtræk-revision

---

fire/cli/niv/__init__.py
fire/cli/niv/ilæg_nye_koter.py
fire/cli/niv/ilæg_nye_punkter.py
fire/cli/niv/opret_sag.py
fire/cli/niv/regn.py

Eliminer resultatregneark: Skriv nye resultater direkte til projektregneark.
Det er mere kompliceret end man skulle tro, men det forenkler alle arbejdsprocesser.

Skriv resultater direkte til projektregneark

---

fire/api/_firedb_hent.py
fire/api/_firedb_indset.py
fire/api/model/punkttyper.py
fire/cli/niv/__init__.py
fire/cli/niv/ilæg_nye_koter.py
fire/cli/niv/ilæg_nye_punkter.py
fire/cli/niv/ilæg_observationer.py
fire/cli/niv/ilæg_revision.py
fire/cli/niv/luk_sag.py
fire/cli/niv/opret_sag.py
fire/cli/niv/udtræk_revision.py
test/test_punkt.py

En overhaling af `fire niv udtræk-revision` og `fire niv ilæg-revision`. Plus enkelte generelle forbedringer. Se commits for detaljerne.
Closes #259

Opdater revision

---

fire/cli/niv/_læs_observationer.py

`fire niv læs-observationer` smider en `UnicodeDecodeError` ved læsning af vedhæftede fil. Læsning ser ud til at fungere når man ikke specificerer en encoding, så derfor prøves først med UTF-8 og faldes tilbage på "almindelig" filåbning. Umiddelbart ser det ud til at et kald af `open()` uden encoding er den simpleste vej frem, men jeg mindes at der var problemer med encoding i nogle filer, så måske det her er den sikreste vej frem. Projekt- og observationsfil vedhæftet i bunden.
```
(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\CAT_HABY>fire niv læs-observationer 2021_CAT_HABY_VER6
Så kører vi
Importerer observationer
Traceback (most recent call last):
File "C:\Users\b012858\Miniconda3\envs\fire\Scripts\fire-script.py", line 33, in <module>
sys.exit(load_entry_point('fire', …
```

Forsøg at undgå UTF-8 dekodningsfejl ved læsning af observationsfiler

---

fire/cli/niv/_regn.py

niv/regn finder selv ud af om man er i gang med en
kontrolberegning eller en endelig beregning.
Derfor er tilvalgsflagene -K[ontrol] og -E[ndelig]
overflødige og fjernes hermed.

Eliminer niv/regn tilvalg -K og -E

---

fire/cli/niv/_ilæg_revision.py

Rest fra en tidligere undtagelseshåndtering

Eliminer anvendelse af udefineret variabel

---

.github/workflows/backport.yml

Samme mekanisme som bruges hos PROJ. Tilføj label med titlen
backport <branch>
hvor <branch> er den branch der skal backportes til. Nemt.

Tilføj backport action

---

fire/cli/niv/_læs_observationer.py

Fjern ikke tabte punkter fra observationsregneark

---

fire/cli/niv/_læs_observationer.py

niv læs-obs: gem obstype i geojson-output

---

fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_nye_koter.py
fire/cli/niv/_ilæg_revision.py

Undgå indlæsning af tomme rækker fra excel-filer

---

fire/cli/info.py
fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_nye_punkter.py
fire/cli/niv/_ilæg_revision.py
fire/cli/niv/_læs_observationer.py
fire/cli/niv/_udtræk_revision.py

Funktionen normaliser_placeringskoordinat() er,
i overensstemmelse med traditionel nomenklatur,
omdøbt til normaliser_lokationskoordinat().
Den er desuden generaliseret til at håndtere både omsætning
fra geografiske geometriobjektkoordinater til UTMbaserede
lokationskoordinater, og omvendt.
Konsekvensrettelser og tilpasninger er indført overalt i kodebasen.
Resolves #380

Forbedret håndtering af lokationskoordinater

---

fire/cli/niv/_udtræk_revision.py
test/niv/test_niv.py

Tillad brug af små bogstaver ved angivelse af opmålingsdistrikt

---

fire/cli/niv/_udtræk_revision.py

Diverse revisionsforbedringer

---

fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_revision.py
fire/cli/niv/_luk_sag.py
fire/cli/niv/_udtræk_revision.py

Diverse forbedringer af `fire niv ilæg-revision`.

Diverse forbedringer af fire niv ilæg-revision

---

fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_nye_punkter.py
fire/cli/niv/_ilæg_revision.py

Tilføj regionskode ved oprettelse af nye nivellementspunkter

---

docs/installation.rst
docs/konfiguration.rst

Fixes #407 
* Flyt test af installation til efter fire.ini er placeret
* Opdater eksempel på response til FIRE 1.1.0

Opdater dokumentation

---

docs/conf.py
docs/installation.rst

Bruges i installationsvejledningen.
Closes #409

Tilføj {FIREVERSION} makro til Sphinx docs

---

fire/cli/main.py

Tre mindre tastefejl i main.py rettet.

Tastefejlsrettelser

---

setup.py

setup.py benytter ikke os og subprocess

Fjern et par overflødige imports

---

.travis.yml
HOWTORELEASE.md

Byg og publiser kun dokumenation fra maintenance branch

---

LICENSE

Vi har også skrevet kode og dokumentation i 2021 - så lad os få indeværende år med i LICENSE-filen

Mangfoldiggørelsesrettighedsangivelsesaktualisering

---

fire/cli/niv/_regn.py

Registrer gyldighedstidspunkt for nyberegnede koter korrekt.
Resolves #425

Gyldighedstidspunkt for nyberegnede koter.

---

fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_nye_koter.py
fire/cli/niv/_ilæg_observationer.py

Refaktoriser skriv_ark() så replace('nan', '') kaldes centralt.

---

.github/workflows/docs.yml
.github/workflows/python-package-conda.yml
HOWTORELEASE.md
environment-dev.yml

Baseret på Githubs skabelon og den eksisterende .travis.yml

Github actions conda workflow

---

fire/cli/niv/_regn.py

niv regn: Giv fastholdte punkter korrekt tidsstempel

---

fire/cli/niv/_ilæg_revision.py

I PR #440 løstes problemet i `fire niv ilæg-revision` med ilægning af "usynlige" blanktegnsværdier. Uheldigvis blev der ikke taget højde for "Sluk"-søjlen i revisionsregnearket, så rettelsen medførte at det blev umuligt at slukke for attributter. Den uhensigtsmæssighed rettes her. Samtidig strammes lidt op på ilægningskoden generelt og der puttes et par kommentarer på et par af de mere kryptiske kodeelementer

Forbedret revisionsilægning

---

fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_nye_koter.py
fire/cli/niv/_ilæg_nye_punkter.py
fire/cli/niv/_ilæg_observationer.py
fire/cli/niv/_ilæg_revision.py
fire/cli/niv/_luk_sag.py
fire/cli/niv/_læs_observationer.py
fire/cli/niv/_netoversigt.py
fire/cli/niv/_regn.py
fire/cli/niv/_udtræk_revision.py

Udsted advarsel hvis niv-regneark skabt med en tidligere version bruges

---

docs/workshop/workshop.rst
fire/cli/niv/__init__.py
fire/cli/niv/_regn.py

Resolves #453
Afventer kommentarer fra @ErikLysdal
Består af to commits, som ikke bør squashes.

Fastholdte punkter i endelig beregning

---

fire/api/_firedb_indset.py
fire/api/firedb.py
fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_nye_koter.py
fire/cli/niv/_ilæg_nye_punkter.py
fire/cli/niv/_ilæg_observationer.py
fire/cli/niv/_luk_sag.py
fire/cli/niv/_læs_observationer.py
fire/cli/niv/_regn.py

Rundt omkring er der en del ikke-anvendte imports som pylint pipper over. Jeg har været på rundtur og fjernet dem hvor flagningen klart ser ud til klart at være korrekt.

Fjern ikke-anvendte imports

---

environment-dev.yml
environment.yml

Opdater pyproj

---

fire/io/bernese.py
test/test_bernese.py

Indlæser døgnresidualer fra ADDNEQ-fil. Antallet af residualer er varierende, så det gives som en liste

Tilføj indlæsning af døgnresidualer

---

fire/cli/info.py
fire/cli/niv/_netoversigt.py
fire/io/bernese.py
fire/io/regneark/__init__.py
scripts/load_shapefile.py
test/test_grafik.py

Et par småtilretninger der følger PEP8  E203, E711, E712, E713.

Et par PEP8 tilretninger

---

fire/io/bernese.py
test/test_bernese.py

Se commit beskeder for yderligere detaljer.

BerneseSolution: Undgå fejl ved kovariansmatrixberegning og gør sorterbar

---

docs/tips/genfundet.rst
docs/tips/index.rst

Tips og tricks: Genfundet punkt

---

fire/cli/niv/__init__.py

I stedet for at skrive det højestrangerende ident i id-feltet skrives
nu landsnummeret og hvis der findes et GI-nummer angives det under
GI-attributten.
Det efterlever ønske om i QGIS at kunne sætte label for et punkt til
enten landsnummerets løbenummer *eller* GI-nummeret. Dette gøres
simpelt ved at sætte labelreglen til:
if("GI"  <> '', "GI", regexp_substr("id", '\\d+$'))
En demofil findes i dette zip-arkiv: [flaf-punkter.zip](https://github.com/Kortforsyningen/FIRE/files/8097918/flaf-punkter.zip)
Closes #491

Tilføj GI kolonne til punkt geojson-filer

---

fire/api/firedb/hent.py
fire/io/regneark/__init__.py

Løser problemer med manglende meteorologiske data i observationsudtræk, samt fejlkonstrueret query i observationsudtræk.
Closes #586
Closes #587

Fix fejl i niv udtræk-observationer

---

.github/workflows/tests.yml
environment-dev.yml
fire/api/niv/udtræk_observationer.py
fire/cli/niv/_ilæg_revision.py
fire/cli/niv/_udtræk_observationer.py
fire/cli/niv/_udtræk_revision.py
fire/cli/typologi.py
fire/herred_sogn.py
test/api/niv/test_ilæg_revision.py
test/api/niv/test_udtræk_observationer.py
test/cli/test_typologi.py
test/cli/test_udtræk_revision.py
test/fire/test_herred_sogn.py

Disse ændringer er en mere omfattende mængde rettelser, der blev til for at forstå koden bedre ved gennemlæsning, da #606 skulle løses (blev løst med #608).

Refaktorisér udtræk/ilæg revision

---

fire/cli/info.py
fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_nye_punkter.py
fire/cli/niv/_ilæg_observationer.py
fire/cli/niv/_ilæg_revision.py
fire/cli/niv/_læs_observationer.py
fire/cli/niv/_netoversigt.py
fire/cli/niv/_opret_sag.py
fire/cli/niv/_regn.py
fire/cli/søg/punkt.py

Erstat sys.exit() kald med raise SystemExit

---

sql/sweep_db.sql

Det gik lige hurtigt nok da dette script blev lavet...

Fjern misvisende kommentar i sql-script

---

fire/cli/niv/__init__.py
fire/cli/niv/_ilæg_revision.py
fire/cli/niv/_udtræk_revision.py
fire/io/regneark/__init__.py

Overskriften var det egentlige problem der skulle løses. Jeg fandt et par andre ting i processen.

Fjern afsluttende mellemrum ved ilægning af nye punktinfo og andre småting

---

fire/cli/info.py
fire/cli/søg/__init__.py

Et par småting jeg studsede over under FIRE kurset

Ændringer i hjælpetekster

---

fire/cli/niv/_regn.py

Så har jeg lavet en fuldstændig ren fork, som burde være identisk med SDFIdk/FIRE, bortset fra ændringer i _regn.py

Refaktorisering af _regn.py

---

.github/workflows/backport.yml

To ændringer:
1. Brug nyeste ubuntu image (der er fejlet de sidste par måneder pga forældet ubuntu 18 image)
2. Opdater til nyeste version af backport action

Opdater backport action

---

fire/cli/niv/_luk_sag.py

Gem alle relevante filer i db ved lukning af sag

---

fire/api/model/tidsserier.py

Udelukkende for at være konsistent med resten af koden.

Ændr rækkefølgen på GNSSTidserie.z og GNSSTidsserie.Z

---

docs/installation.rst

Docs: Tilføj note om deaktivering af miljø ved afinstallation

---

fire/cli/niv/__init__.py

I sitatuationer hvor der ikke står en kote i regnearket opstår der uden denne ændring fejl i skrivning af geojson-filerne. Problemet er, at float-funktionen ikke ved hvad den skal stille op med None. Det tages nu hånd om ved at håndtere de tre tilfælde der kan opstå ved generering af punkt features:
1. punkter uden ny og gammel kote
2. punkter uden ny kote, men med gammel kote (fastholdt kote)
3. punkter med ny og gammel kote
Med denne ændring sættes flere værdi i geojson-filerne til "none" (fremstår som "null" i QGIS) hvis ikke værdierne er kendte, herunder GI-nummer, kote og deltaværdi (for koten). Tidligere kan de have fremstået som en tom streng eller 0.0, hvilket ikke altid er korrekt.

Undgå fejl i skrivning af geojson filer under læsning af observationer

---

sql/views.sql

Ændringer i forbindelse med opdatering af VisFix2

Tilføj GI ident og afmærkningsoplysninger til `v_fikspunkter_dk`

---

fire/__init__.py
test/test_observation.py

Inkl. en lille forbedring af test-suiten som ellers fejlede i visse tilfælde

Gør klar til version 1.7.0

---

fire/cli/indlæs/bernese.py

Slet forkert afsnit i bernese.py dokumentation

---

.github/workflows/tests.yml
scripts/get_oracle_pkgs.sh

Løser problem med Oracle installation og simplificerer action-opsætning en smule.

Fix CI oracle install

---

sql/views.sql

Tilføj tabstidspunkt til view over tabtgåede punkter

---

sql/views.sql

Er rullet ud på test og prod. Det virker fint :)

Tilføj view til KDI vandstandmålere

---

fire/api/firedb/__init__.py
fire/api/firedb/base.py
fire/api/firedb/indset.py
fire/api/firedb/luk.py

Fix fejl ved lukning af fikspunktregisterobjekter

---

fire/cli/grafik/__init__.py

Fixes #682 
Se også kommentaren: https://github.com/SDFIdk/FIRE/issues/682#issuecomment-2293664840

Fix #682: Flush buffer så små filer kan åbnes med fire grafik vis

---

fire/api/model/tidsserier.py
test/api/tidsserier/test_tidsserie_attributter.py

Forsøg på at dele nogle af mine ændringer op i spiselige bidder. Med "generelle" forstås ting, som ikke har med "tidsrækkeanalyse" at gøre. Beholder denne PR i draft, hvis der skulle komme flere ændringer som ikke har med tidsrækkeanalyse at gøre.
Ændringer til tidsrækkeanalyser (som også ligger i Tidsserie-api) vil komme i separat PR senere.

Tilføjelser og ændinger til det "generelle" Tidsserie-api

---

sql/views.sql

Denne har været klar længe, men nu kommer den afsted efter lidt afstøvning og finpudsning. Har lagt dem på test-databasen, men de kan også godt lægges på prod nu.

Tilføj  views til visning af punktsamlinger og tilhørende tidsserier jessenpunkter

---

fire/api/firedb/indset.py
fire/api/model/punkttyper.py
fire/cli/info.py
test/info/test_info.py

Bemærk: Dette PR ligger oven på #773 og skal først derfor først merges efter #773 er blevet merget!

Punktsamling 2: Tilføjelser til fire info kommandogruppen

---

fire/api/model/punkttyper.py
fire/cli/niv/__init__.py
fire/cli/niv/punktsamling.py
fire/io/regneark/arkdef.py
test/test_punktsamling.py

Bemærk: Dette PR ligger oven på https://github.com/SDFIdk/FIRE/pull/774 og skal først derfor først merges efter https://github.com/SDFIdk/FIRE/pull/774 er blevet merget!

Punktsamling 3: Tilføj nye niv-underkommandoer til håndtering af punktsamlinger og tidsserier

---

.github/workflows/tests.yml
docs/apps/info.rst
fire/api/firedb/hent.py
fire/api/model/sagstyper.py
fire/cli/info.py

Formålet er, at gøre det let at få information om en sag og dens tilhørende sagsevents. Enkelte tilpasninger lavet til `fire info sag` for at gøre outputtet lettere at fordøje. Den væsentligste ændringer er tilføjelsen af `fire info sagsevent`, der nu tillader opslag af et specifikt sagsevent. Værktøjet er ikke perfekt, men giver mulighed for lettere at gå på opdagelse i databasens indhold uden at skulle i gang med omfattende SQL-forespørgsler.
Herunder et par eksempler på  `fire info sag` og `fire info sagsevent`:
Ny visning af sagsinfo:
```
fire info sag --db prod ab910295-c23f-4272-8b26-1b152631afd2
------------------------- SAG -------------------------
Sagsid        : ab910295-c23f-4272-8b26-1b152631afd2
Oprettet      : 2023-05-02 09:37:35.642332
Sagsbehandler : B004276
Status …
```

Forbedring af sagsopslag med `fire info`

---

environment.yml

@krebslw vil du ikke prøve det her miljø af? Jeg har får en dum fejl når jeg prøver at oprette det på Windows, men det fungerer på Linux. Jeg har en mistanke om at det er noget på min maskine der skaber problemet, og ikke selve miljøopsætningen den er galt med

Opdater afhængigheder i fire-miljø

---

sql/views.sql

Viewet indeholder alle nivellement-observationer og tilhørende info om sag og sagsevent.
Kan fx bruges til at filtrere på observationstidspunkt for at danne et overblik over årets afsluttede/uafsluttede nivellementsopgaver.

Opret view v_alle_niv_obs

---

sql/views.sql

Der er forskel på geometriske og trigonometriske observationer.

Ret fejl i v_alle_niv_obs

---

sql/views.sql

efter ændringsønske fra K.Loftlund. Derudover:
- omdøb beregningstidspunkt til dvr90_t på v_fikspunkter_dk
- tilføj automatisk opdatering af v_alle_niv_obs
Viewsne er allerede opdateret på prod.

Tilføj oprettelsesdato i v_fikspunkter_dk og andet småt

---

fire/cli/niv/_regn.py
fire/cli/niv/punktsamling.py

Fix diverse små bugs

---

fire/api/firedb/hent.py
fire/cli/info.py

I  ``info punkt``: Anvend ``-H`` til at søge blandt afregistrerede identer

---

environment-dev.yml
src/fire/api/firedb/base.py
src/fire/api/firedb/hent.py
src/fire/api/niv/udtræk_observationer.py
test/test_observation.py

samt gør så der søges blandt både opstillings- og sigtepunkter

hent_observationer_naer_geometri:  Fix ugyldige geometrier

---

docs/apps/niv.rst
src/fire/cli/info.py
src/fire/cli/niv/__init__.py
src/fire/cli/niv/_luk_sag.py
src/fire/cli/niv/_åbn_sag.py

Mulighed for at genåbne en sag er tilføjet, og en fejl i `fire info sag` fikset.
Closes #834

Opdateringer til fire niv og fire info

---

docs/api/fire.api.niv.rst
src/fire/api/niv/regnemotor.py
src/fire/cli/niv/__init__.py
src/fire/cli/niv/_netoversigt.py
src/fire/cli/niv/_regn.py
test/api/niv/test_netanalyse.py
test/api/niv/test_regnemotor.py

Der mangler stadig nogle finpudsninger ..  Men strukturen i det er som den skal være.

Tilføj regnemotor

---

src/fire/api/niv/udtræk_observationer.py
src/fire/cli/info.py
src/fire/cli/niv/__init__.py
src/fire/cli/niv/_læs_observationer.py
src/fire/cli/niv/_regn.py
src/fire/cli/niv/_udtræk_observationer.py
src/fire/io/geojson.py
test/api/niv/test_udtræk_observationer.py

Og opret skriv_sagsrapport_geojson som fixer #854 
Fixes #854

Faktoriser skrivning af geojson filer ud i IO-modulet

---

src/fire/cli/info.py

Det gik lidt stærkt, så der var gået ged i den med logikken omkring kontrol-flowet i `info sag`.

Fix bug introduceret i PR #855
