SDFIdk/FIRE

fireapi/firedb.py, fireapi/model/__init__.py
If user tries to delete a RegistreringTidObjekt, then turn this into an update where registreringtil is set to sysdate.
=> Turn delete of RegistreringTidObjekt into update instead

fireapi/model/punkttyper.py, fireapi/model/sagstyper.py, test/conftest.py
This reverts commit e24c4c9b3bc7a7ae592eaaa6234669fa40284817 because @AsgerPetersen is right that in this case the implicit is < than the explicit.
=> Revert "Prefer backref when possible"

fireapi/firedb.py, fireapi/model/punkttyper.py
I am testing the API by writing a simple application that grabs data from the database. I come across minor problems while doing so. This PR contains the fixes I come up with for those problems.
The PR started as a fix to this problem, seemingly caused by an update to the DDL:
```
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00904: "PUNKTINFO"."REELTAL": invalid identifier [SQL: 'SELECT punktinfo.registreringfra AS punktinfo_registreringfr_1, punktinfo.registreringtil AS punktinfo_registreringti_2, punktinfo.objectid AS punktinfo_objectid, punktinfo.sagseventid AS punktinfo_sagseventid, punktinfo.infotype AS punktinfo_infotype, punktinfo.reeltal AS punktinfo_reeltal, punktinfo.tekst AS punktinfo_tekst, punktinfo.punktid AS punktinfo_punktid \nFROM punktinfo \nWHERE :param_1 …
```
=> Various fixes to minor things

fireapi/__init__.py, setup.py
We need to be able to install fireapi so other apps can use it. This adds a very basic setup script.
=> Add basic setup script

fireapi/firedb.py, fireapi/model/punkttyper.py, test/test_punktinformationtype.py, test/test_srid.py
E.g. `PunktInfo._infotypeid` -> `PunktInfo._infotypeid` and
`PunktInfoType.infotype` -> `PunktInfoType.name` with the latter being
justified by use cases such as
```
p = firedb.hent_punkt(...)
p.punktinformationer[0].infotype.infotype
```
which rather clumsy. Accessing the infotype as
```
p.punktinformationer[0].infotype.name
``` 
reads much better.
Similar changes has been made to `Srid` and `ObservationsType`.
No idea what the impact on the tests are - will fix if they fail :-)
=> Unhide id's and rename type accessors

.circleci/config.yml
Vi skal som minimum bruge Oracle 12c hvilket ikke findes i et let tilgængelig Travis setup, så derfor genopliver jeg CircleCI. Det er ikke perfekt da de to docker images der benyttes er nogle sorte bokse vi ikke har ordentligt indsigt i. Forhåbentligt er der på et tidspunkt en der gider lave et Travis setup der bruger en nyere Oracle version.
=> Genaktiver CircleCI

.travis.yml
... for at kunne undgå at CircleCI kører på gh-pages branch
=> Opgrader til ghpages deploy v2 

.circleci/config.yml, fireapi/model/__init__.py, fireapi/model/punkttyper.py, test/fixtures/sql/fikspunkt_forvaltning.sql, test/test_koordinat.py
Tilpas API som konsekvens. 'artskode' er en efterladenskab
fra REFGEO som vi ikke vil eksponere via API'et, derfor er kolonnen
markeret som "excluded property".
So far bare en test af om det går godt at tilføje artskoden på denne måde. Merges først når DDL er opdateret i FIRE-DDL repositoriet.
=> Opdater DDL med KOORDINAT.ARTSKODE kolonne

sql/ddl.sql
Første commit fjerner overflødigt whitespace. Den faktiske ændring fremgår af andet commit.
=> Fiks fejlmeddelelse ved indsættelse af sagsevent uden tilhørende sag

fire/cli/mtl.py
Et par steder var uddata ikke sorteret, og kom derfor til at afhænge af den ikke-deterministiske ordning af set()-strukturer. Med denne tilpasning kommer uddata (fx nabopunkter) altid i samme ordnede rækkefølge.
=> Forbedret reproducibilitet ved mere konsekvent sortering af uddata

.circleci/config.yml, fire/api/model/punkttyper.py, sql/ddl.sql, test/conftest.py, test/sql/testdata.sql, test/test_beregning.py, test/test_srid.py
Tilføjer et mere eller mindre komplet testdatasæt, der motionerer de essentielle dele af datamodellen. Se kommentarer `test\sql\testdata.sql` for en beskrivelse af testdatasættet.
Forud for inklusion af testdatasættet er der lavet mindre ændringer i både API test-koden og DDL'en, da der var enkelte fejl og mangler der blev afsløret undervejs i arbejdet med det testdatasættet. Det drejer sig specifikt om uhensigtsmæssige test-fixtures og manglende triggers på udvalgte tabeller.
=> Tilføj testdatasæt

fire/api/firedb.py, fire/api/model/punkttyper.py, test/test_koordinat.py
`_close_existing_koordinat` gør grundlæggende det samme som triggeren
BID#KOORDINAT, hvorfor funktionen er overflødig. Ved at håndtere
afregistreringen på databaseniveau sikrer vi os at der ikke indsættes
fejlbehæftet data pga fejl i kode eller brugen af API'et.
Tests tilføjet for at verificere at triggeren fungerer efter hensigten.
=> Afregistrer koordinater med DB trigger fremfor API-kode

fire/__init__.py, fire/api/firedb.py, fire/api/model/punkttyper.py, fire/api/model/sagstyper.py, fire/cli/mark.py, test/conftest.py, test/test_punkt.py, test/test_sag.py
Tilføjer funktionen `fire.uuid` som kaldes alle steder hvor der før blev
skabt uuid'er med `str(uuid.uuid4()). Desuden er Sag, Sagsevent og Punkt
udvidet til at automatisk indsætte et UUID som ID ved indlæsning i
databasen. Dette fjerner en del boilerplate kode ved instatiering af disse
klasser.
Closes #92
=> Generer UUID'er automatisk ved indsættelse

fire/api/model/sagstyper.py, sql/ddl.sql, test/sql/testdata.sql, test/test_punktinformation.py
- Fjerner eventtypen "beregning", da samme funktionalitet er dækket af "koordinat_beregnet". #116
- Fjerner ubrugte namespace tabeller #128
- Strammer op på kommentarer
- Tilføjer db trigger der sørger for at afregistere punktinformation korrekt ved opdatering
=> DDL opdateringer

fire/api/model/punkttyper.py
Nye koordinater der indsættes med FIRE skal ikke have sat en artskode, derfor ændret til at indsætte `NULL` hvis ikke der bedes om andet.
=> Sæt default artskode til NULL fremfor 'net af lav kvalitet'

fire/cli/mtl.py
Der indgår nogle sære tegn i rådatafiler, steder hvor konteksten tilsiger at der skal stå "æ". Derfor disse rettelser, der primært sørger for at sikre at ind- og udlæsning  foregår med utf-8. Desværre løser det ikke problemet: Placeholdertegnene er introduceret før rådatafilen når frem til FIRE. Men præciseringen i koden har også værdi i sig selv - om ikke andet så fordi den gør det klokkeklart at problemet ligger et andet sted
=> Mindre forbedring af dataimport

fire/cli/mtl.py
Observationsligninger for holdte ("constrained") punkter overskrev hinanden, da der manglede en rækketælleropdatering. Det er fikset her
=> Indsæt manglende rækketæller for 'holdte' punkter

fire/api/firedb.py, fire/api/model/sagstyper.py, test/conftest.py, test/test_beregning.py, test/test_koordinat.py, test/test_observation.py, test/test_punkt.py, test/test_punktinformation.py, test/test_sag.py
Lukkefunktioner tilføjet for punkt, koordinat, punktinfo, observation og
beregning. Lukning af koordinater, punktinfor og observationer er
simpelt: Sæt registreringtil og sagseventtilid til noget andet end Null.
Det forholder sig anderledes med punkt og beregning. Når en beregning
lukkes, lukkes automatisk også alle tilknyttede koordinater, da de
nødvendigvis må være fejlbehæftede hvis det er nødvendigt at nedlægge en
beregning. Efter samme princip nedlægges så godt som al tilknyttet
information til et punkt når det lukkes. Det vil sige punktinfo,
kooordinater, geometriobjekt og observationer hvor punktet indgår.
Lukning af et punkt forventes kun gjort ved meget ekstraordinære
tilfælde.
Closes #23
=> Tilføj luk_-funktioner

fire/cli/mark.py
Observationsfilformatet er skiftet en del det sidste år. Dette PR indfører den absolut mindste tilpasning for at understøtte nyere formater, mhp at kunne krydschecke op mod mtl.py
=> mark.py: Håndter nyere observationsformater.

fire/api/firedb.py, test/test_punktinformationtype.py
Der kan potentielt laves mange kald for at få det samme objekt ud af
databasen. Nu caches de up front, så der ikke spildes unødig tid på
databaseopslag der ikke er nødvendige.
=> Indfør caching i FireDb.hent_punktinformationtype

fire/cli/info.py
Ansporet af at
fire info punkt G.M.902
returnerede det samme punkt to gange. Årsagen til dette skal findes i,
at punktet har en ATTR:beskrivelse der starter med "G.M.902". Da der
manglede et join på punktinfotype blev denne ikke sorteret fra. Nu tages
kun punktinfo af typen "IDENT:..." i betragtning, som det hele tiden var
intentionen.
Fixes #152
=> Tag punktinfotype i betragtning ved ident-opslag

fire/cli/info.py
Fungerer i det store hele for nivellementsobservationer (som er hvad @majbrittws har brug for lige nu), men afstandsafhængig varians ser underlig ud @kbevers kan du pege mig i retning af migreringskoden for det? - der må være noget galt.
Desuden er jeg stødt på et par mærkelige observationer, der hævder at bestå af -31072 opstillinger:
` fire info punkt -O K-63-09007`:
```
--- OBSERVATIONER ---
Antal observationer til:  4
G 0 1997-07-15 12:00:00    +1.125000 100.0 10    K-63-09004   K-63-09007      1.581139 0.001000 +000.00
G 0 1997-05-23 18:02:00    +2.289700 029.1 -31072    G.M.901      K-63-09007      0.170587 0.000000 +000.00
G 0 1997-02-19 12:00:00    +0.441000 100.0 10    K-63-09010   K-63-09007      1.581139 0.001000 +000.00
G 3 1988-04-15 11:18:00    +2.288820 029.9 1    G.M.901 …
```
=> info punkt - option til udskrivning af observationer

fire/api/gama/reader.py, fire/api/model/__init__.py, fire/api/model/punkttyper.py, fire/cli/info.py, test/conftest.py, test/test_beregning.py, test/test_observationtype.py
Indeholder to commits:
Første commit i dette PR sørger for at test-suiten afvikles mere effektivt. 
Andet commits indfører en Boolean enum. Istedet for at API-brugeren skal gættes sig til korrekt stavning af enten 'true' eller 'false' indføres en Boolean enum istedet.
=> Tilføjelse af Boolean enum

sql/ddl.sql
Fjernet overflødigt "end;", snævret listen af SRID namespaces ind til de
faktisk brugte og fjernet en del af en kommentar der ikke længere er
gyldig.
=> DDL: Småjusteringer

fire/cli/mtl.py
Skriver observationer og punkter med relevante attributter til to geojsonfiler.
Overvejede at bruge Fiona, mhp at kunne vælge vilkårligt outputformat frem for blot geojson. Men Fiona er klart lettere at bruge til at læse og forlænge med, end til at skrive nye filer fra bunden. Så det kommer først til at ske når der viser sig et oplagt behov. Koden her er tilstrækkelig kompakt og lokaliseret til at den ved den lejlighed kan fjernes med brækjern og give plads til Fionas fine fingre.
=> MTL: GeoJSON for punkter og observationer

fire/cli/mtl.py
Observationsidentifikation via 'extern'-attributter blev indført til ære for os. Vi må hellere bruge dem: Der bliver behov for dem ifbm. håndtering af beregningselementer i databasen.
=> MTL: Indført journalside som 'extern'-identifikation i Gama inddatafil

fire/api/model/sagstyper.py, fire/cli/info.py
Sagsinfo.beskrivelse og Sagsevent.beskrivelse må gerne være tomme,
derfor indføres der et par tjeks der undgår exceptions når de er tomme.
Opfølgning på #174 der altså ikke var helt færdig alligevel
=> fire info sag: Undgå exceptions når beskrivelser ikke findes

fire/api/firedb.py, fire/api/model/punkttyper.py, test/test_ident.py, test/test_punkt.py
Med afsæt i https://github.com/Kortforsyningen/FIRE/pull/183#issuecomment-642088266.
Hovedformålet med dette PR er at indføre caching af punkter i `FireDb`, samt at tilføje en funktion der gør det muligt at trække en række punkter ud ved hjælp af en liste af identer. For at kunne håndtere caching ordentligt (et punkt kan identificeres ved mange identer) er der indført bedre mekanismer til at sortere og udtrække identer for et punkt.
Ved review af dette PR bør hver enkelt commit læses for sig. Se commit messages for yderligere kommentarer til koden. Bemærk at `FireDb.hent_punkt_list()` er implementeret så simpelt som muligt. Jeg har ganske kort kigget på hvor lang tid det tager at trække punkterne ud på denne måde og det ser umiddelbart ikke ud til at være den store tidsrøver. Hvis det …
=> Caching af punkter og indførelse af FireDb.hent_punkt_liste()

fire/cli/mtl.py
Opfølgning på #172, især animeret af meget nyttige kommentarer fra @kbevers
Reparationer af fejl og uhensigtsmæssigheder der enten skyldes
committerens personlige tåbelighed, manglende apriorierfaring
med forskellige elementer af Python herself, eller hændelige
uheld i implementeringsfasen.
* Anvend Punkt-objektet direkte, frem for at stige hele vejen ned i
fire.cli.firedb-objektet hver gang en lille del skal fremfindes.
* Ombyt anvendelse af enkelt- og dobbeltcitationstegn i f-strenge,
så det matcher Blacks forkærlighed for de dobbelte
* Indfør a priori check for om uddatafil er låst af Excel
=> MTL: Reparer API-anvendelse, citationstegn o.a.

fire/cli/info.py
"info sag ..." rapporterer at alle sager er lukkede: sag.aktiv=True matcher åbenbart ikke Boolean.TRUE. Jeg forstår ikke hvorfor det er sådan, men når man retter Boolean.TRUE til True bliver rapporteringen korrekt
=> Korriger rapporteret sagsstatus for "info sag"

test/sql/testdata.sql
Indsæt testdata på samme måde som data skal indlæses i produktion.
Det er vigtigt at sagsevents og alt tilhørende data indlæses i een og
samme transaktion, derfor fjernes en række overflødige commits.
=> Lav transaktionbaserede indsættelser af testdata

fire/cli/info.py
Indfører option `-s/--søg`, så man kan sige:
```sh
$ fire info infotype -s skruepløk    
"skruepløk" matcher følgende punktinfotyper:    
AFM:1952   Skruepløk, 1.5 m lang.               
AFM:1953   Skruepløk, 2.0 m lang.               
AFM:1963   Skruepløk,1.5 m lang, med fedtpatron.
AFM:2950   Skruepløk.                           
AFM:2951   Skruepløk, 1.0 m lang.               
```
=> Indfør generel søgning for fire info infotype

fire/cli/info.py
En søgning uden resultat vil føre til en nullængdeuddataliste, som får max(...) til at falde død om, da den i så fald ikke har noget fornuftigt at resultere.
=> fire info infotype: Undgå bombe ved manglende match

fire/api/_firedb_hent.py, fire/api/_firedb_indset.py, fire/api/_firedb_luk.py, fire/api/firedb.py
Med henblik på at øge overskueligheden af FireDb-klassen splittes
den op i flere filer. For nuværende er tre grupper er metoder flyttet
til seperate moduler: Hent, indsæt og luk. Skulle der i fremtiden
opstå flere naturlige grupperinger, fx søg eller tilknyt, bør disse
også udskilles i seperate moduler.
Der er *ikke* ændret i funktionaliteten af de enkelte metoder.
=> Split FireDb op i flere filer

fire/api/_firedb_hent.py, fire/api/firedb.py, fire/cli/info.py
Introducerer `soeg_punkter(ident)`, som matcher `ident` med bruge af LIKE, så man kan søge fx alle højdefikspunkter i et opmålingsdistrikt: `hent_punkter_joker("40-12-09%")`.
Funktionaliteten har tidligere været indbygget i `hent_punkter()`, men er åbenbart ikke blevet merget på det tidspunkt. Det er ellers intentionen bag `fire info punkt` at man også skulle kunne anføre jokertegn.
=> Hent punkter med jokertegn

fire/api/firedb.py, fire/cli/søg/__init__.py, fire/cli/søg/punkt.py, setup.py, test/test_punkt.py
Bygger oven på #211 
Eksempler:
```
(fire-dev) C:\dev\fire>fire søg punkt K-63-0000% -n 5
K-63-00009          43524
K-63-00008          43523
K-63-00007          43522
K-63-00006          43521
K-63-00005          43520
(fire-dev) C:\dev\fire>fire søg punkt G.M.90% -n 5
G.M.908.1           40-12-09057         210017
G.M.908             40-12-09056         210016
G.M.907.1           40-12-09055         210015
G.M.907             40-12-09054         210014
G.M.906.1           40-12-09053         210013
(fire-dev) C:\dev\fire>fire søg punkt %-V.% -n 5
K-75-09393          K-75-V.12           854144
69-01-09095         69-01-V.7           858816
K-31-V.7            861604
94-01-V.2           862449
K-67-09388          K-67-V.9            875823
```
Det fremgår ikke af ovenstående, men …
=> fire søg punkt

fire/api/_firedb_indset.py, fire/api/firedb.py, test/test_observation.py, test/test_punkt.py
indset_flere_observationer er den naturlige pendant til
indset_flere_punkter: Den indsætter et antal observationer
under samme sagshændelse.
Indfører desuden den manglende test for indset_flere_punkter
og en tilsvarende for indset_flere_observationer. Disse er
dog skrevet helt i blinde og baseret på de eksisterende tests.
=> Introducer indset_flere_observationer

fire/cli/__init__.py, fire/cli/søg/punkt.py
```
>fire info srid EPSG:4258
--- SRID ---
Name:       :  EPSG:4258
Description :  Geografiske koordinater 2D: ETRS89
```
versus
```
>fire info srid --debug EPSG:4258
2020-08-20 14:54:07,728 INFO sqlalchemy.engine.base.Engine SELECT USER FROM DUAL
2020-08-20 14:54:07,729 INFO sqlalchemy.engine.base.Engine {}
2020-08-20 14:54:07,736 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60 CHAR)) AS anon_1 FROM DUAL
2020-08-20 14:54:07,737 INFO sqlalchemy.engine.base.Engine {}
2020-08-20 14:54:07,741 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS NVARCHAR2(60)) AS anon_1 FROM DUAL
2020-08-20 14:54:07,742 INFO sqlalchemy.engine.base.Engine {}
2020-08-20 14:54:07,747 INFO sqlalchemy.engine.base.Engine select value from nls_session_parameters …
```
=> Tilføj --debug flag på fire cli kommandoer

.travis.yml
FireDb smider en exception hvis ikke fire.ini kan findes på
systemet. Vi kopierer den ind i roden af $HOME.
=> Sørg for at fire.ini placeres korrekt på Travis

fire/cli/niv.py
Understøt, til demoformål, testudførelse af ilæg-revision, uden brug af registreret sag
=> Sagsløs dryrun af ilæg-revision

.circleci/fire.ini, fire/api/firedb.py
Med overgang til ny databasehardware og opdateret Oracleversion
er det ikke længere databasenavnet, der benyttes ved forbindelse
til FIREs tilhørende database.
Syntaksen for forbindelse ved hjælp af servicenavnet frem for
databasenavnet, er kun marginalt anderledes end den tidligere
anvendte, men de to er inkompatible. Og da vi stadig skal bruge
databasenavnsyntaksen i CI/test-sammenhæng er det nødvendigt at
indføre en mellemform.
Det er gjort ved at indføre ini-filnøglen "method", som, hvis
den ikke er sat, tildeles værdien "service".
- Hvis "method" (ad eksplicit eller implicit vej) har værdien
"service" forsøger vi at åbne databasen via servicenavnet.
- Hvis "method" eksplicit er tildelt værdien "database" forsøger
vi at åbne databasen via databasenavnet
Den her indførte mellemform er, …
=> Brug hellere servicenavn end databasenavn

fire/cli/niv/__init__.py, fire/cli/niv/ilæg_nye_koter.py, fire/cli/niv/ilæg_nye_punkter.py, fire/cli/niv/ilæg_observationer.py, fire/cli/niv/ilæg_revision.py
Indfør ensartet tilgang til sikkerhedsdialog ("Er du helt sikker på
at du vil skrive til databasen"-agtige spørgsmål) i de 4 database-
ilægningsfunktioner.
Alle funktionerne accepterer nu de to flag '--test' og '--alvor',
hvor '--test' er automatisk forvalgt. Der skrives KUN til databasen
hvis '--alvor' eksplicit er valgt, og kun efter behørig advarende
dialog med fortrydelsesmulighed.
Funktionen 'bekræft()' centraliserer både flaghåndtering og dialog.
Indfør generel brug af funktionen 'find_faneblad()' i stedet for
individuel fuldfed kode alle steder hvor et faneblad skal bruges.
Tilpasset ilæg_nye_koter() til ny arbejdsgang. Den læser nu fra
fanebladet 'Endelig beregning' og skriver til 'Resultat'
=> Strømlining af databaseilægningsfunktionerne

fire/cli/søg/punkt.py
Uden kwargs fejler programmet når default parametre tilføjes.
=> Tilføj kwargs argument til fire.cli.søg.punkt

fire/api/firedb.py
Den tidligere anvendelse af datetime.now... gav to timers fejlstempling i databaseregistreringen af slukkede objekter, i forhold til samtidigt indførte nyoprettede og rettede.
=> Brug databasegenereret tidsstempel ved lukning af fikspunktregisterobjekt

fire/api/model/__init__.py, fire/api/model/sagstyper.py, test/conftest.py, test/test_ddl.py
BID#KOORDINAT
BID#PUNKT
PUNKTINFO_TYPE_VALID_TRG
Tester primært at tidligere objekter afregistreres når et nyt tilføjes
tabellen. Tester derudover også at lukkede Koordinater og Punkter ikke kan
indlæses direkte i databasen (== registreringtil kan kun sættes ved et
UPDATE statement).
=> Test af udvalgte database triggers tilføjet

fire/api/_firedb_hent.py, fire/cli/info.py, fire/cli/søg/punkt.py, fire/cli/utils.py
Indfører samme identopslagslogik i `fire søg punkt` som findes i `fire info punkt`. Derudover fjernes muligheden for søgning med wildcards på punkter i nordatlanten fra `fire info punkt`, da det er logik der ikke længere er aktuel og skulle være fjernet i et tidligere commit.
Closes #238
Closes #242
=> Ident opslag

fire/api/model/punkttyper.py
Jævnfør #254: Det kan desværre lade sig gøre at registrere identer uden navn. Derfor denne robustifikation af identhåndteringskoden. Det løser ikke problemet, men det fjerner symptomet. På en ikke-intrusiv måde, som kan pilles af igen når rodårsagen er elimineret, hvis man stoler 100% på at elimineringen er vandtæt.
=> Håndter identer uden navn

fire/api/firedb.py
Read-onlykontoen, som bør være den primært anvendte, logger ind i et andet skema end administatorkontoen, og kan derfor ikke se tabellerne. Ved at indføre
execution_options={"schema_translate_map": {None: "fire_adm"}},
i create_engine-kaldet i firedb.py præfikses alle tabelnavne uden skema med skemaet "fire_adm"
=> Håndter andre brugerkonti end administratorkontoen

fire/api/firedb.py, fire/api/model/__init__.py, fire/api/model/punkttyper.py, sql/ddl.sql, test/conftest.py, test/gama/test_gama_cli_read.py, test/test_beregning.py, test/test_ddl.py
Lidt af hvert:
1. Opdeling af DDL i sektioner
2. Omformateret så udtrykket er nogenlunde ens over det hele
3. Navngivning strømlinet for index, constraints og triggers
4. Fejlmeddelser oversat til dansk og flere fejlkoder benyttes
5. ISO-format for tidsstempler i DDL.
Closes #248
=> DDL oprydning

fire/cli/niv/ilæg_nye_koter.py
datetime.now() -> sqlalchemy.func.current_timestamp()
=> Få mikrosekunderne med i registreringstidspunktet

fire/api/model/__init__.py
I tilfælde hvor en attribut på et tabelobjekt ikke matcher kolonnenavnet
ville en exception bliver rejst tidligere. Nu forsøges problemet løst
(fx hvor attributten er 'eventtype' men kolonnen hedder 'eventtypeid')
og lykkes det ikke springes attributten over.
Problemet observeret specifikt ved kald af `repr()`på et `Sagsevent` objekt.
=> Forbedr Fikspunktregisterobjekt.__repr__

fire/cli/info.py
#246 skulle indføre markering af slukkede punktinformationer.
Det gjorde den bare ikke. Det gør denne korrektion, derimod.
=> Reparer #246

fire/cli/niv/ilæg_revision.py, fire/cli/niv/udtræk_revision.py
Lidt bedre overblik ifbm punktrevision - både i skærmdialogen og i det udtrukne regneark:
1. Udelad unødvendige punktnavne i udtrækket
2. Læg flere blanklinjer mellem hvert punkt i udtrækket
3. Mere overskuelig skærmdialog under ilægning
=> Udtrækskosmetik

fire/cli/info.py, fire/cli/niv/ilæg_revision.py, fire/cli/niv/udtræk_revision.py
fire info punkt: udskriv kun koordinatspredninger hvis de ikke er None
fire info infotype: medtag infotypeid i søgelister
fire niv ilæg-revision: håndter både punktum og komma som decimalseparator
fire niv udtræk-revision: håndter punkter uden geometri
=> Nogle mindre rettelser som har hobet sig op

fire/api/_firedb_luk.py
I filfælde hvor flere punkter, koordinater, observationer, punktinfo
eller beregninger skal lukkes samtidigt er det uhensigtsmæssigt at
FireDb.luk_*() funktionerne automatisk committer til databasen. Med
dette commit er det nu muligt at fravælge commit (med commit=False) og
udskyde det til senere når alle ønskede objekter er lukkede.
=> Tillad lukning af objekter uden commit til DB

fire/cli/niv/regn.py
Undgå at tidligere udjævningsresultater for punkter,
der fastholdes i ny beregning, bløder igennem til
resultatregnearket.
Resolves #285
=> Overskriv foregående værdier af 'Ny kote', 'Ny σ'

environment-dev.yml, environment.yml, fire/cli/niv/regn.py
update-constrained-coordinates='no' var frarådet
i GNU Gama version 2.09 og blev ikke accepteret
længere fra og med version 2.10
Vi fjerner det uacceptable input og skubber den
anvendte version frem til 2.13
Resolves #280
=> Fjern deprecated option fra gama-localinputfil

environment-dev.yml, environment.yml
Den tidligere anvendte pandas-1.1.2, fungerede
sammen med xlrd-1.2.0. xlrd er imidlertid under
udfasning, fordi dens xml-læser tilsyneladende
udgør en sikkerhedsbrist. Nyere udgaver (post
2.0.0) kan derfor ikke længere læse xlsxfiler,
men kun de aldrende binære xls-filer.
Vi opgraderer derfor fra xlrd til openpyxl og
ved samme lejlighed til en nyere og meget
hurtigere udgave af pandas.
Resolves #281
=> Opdater til pandas-1.2.1 og openpyxl-3.0.6

environment-dev.yml, environment.yml, fire/cli/niv/__init__.py
Efter opdatering af pandas til 1.2.1 sker kontrollen for
om en excelfil er åben allerede når writerelementet
instantieres, ikke først når man forsøger at skrive til
filen.
Det er i modstid med logikken bag "spørg brugeren om man
har glemt at lukke arket før skrivning" i skriv_ark(), som
derfor opdateres.
Da vi for nylig har introduceret afhængighed af openpyxl
behøver vi ikke længere at bruge xlsxwriter til skrivning
af excelfiler: Den reparerede logik benytter nu openpyxl
og xlsxwriter er fjernet fra miljødefinitionsfilerne.
Endvidere er fejlbeskrivelsen i brugerdialogen forbedret,
så den er konsistent mellem find_faneblad() og skriv_ark().
=> Reparer skriv_ark() efter opdatering af pandas

fire/cli/niv/ilæg_nye_koter.py, fire/cli/niv/ilæg_observationer.py
MGL-observationer blev fejlagtigt instantieret med value4=None og
value7=None.
value4 er den, for gamle MGL-målingers vedkommende, registrerede
refraktionsrelaterede koefficient. Den benyttes ikke længere, men
er i DDL defineret som non-null - så vi sætter den nu til 0 istf
None.
value7 angiver, med værdien 1,2,3 om observationen hører til et af
de tre præcisionsnivellementer. value7 er også defineret som non-
null. Vi må derfor sætte den til 0, i overensstemmelse med DDLen.
Sagshændelser vedrørende koteopdateringer blev i regnearket tids-
stemplet med tekststrengen "CURRENT_TIMESTAMP", som ved skrivning
til databasen udfoldes til nanosekundopløsningstidsstempel. Excel
er mindre samarbejdsvillig desangående, så vi må i stedet trække
en værdi fra Pandas' Timestamp.now()-funktion.
Med disse …
=> Justering af observationers/koters persistering

environment-dev.yml, environment.yml
Fastlås MAJOR- og MINOR-elementerne i alle semantiske versionstripler
for pakker anvendt i FIREs conda-pakkemiljøer "fire" og "fire-dev".
PATCH-elementerne får lov at flyde, så vi får sikkerhedsopdateringer
indført ved miljøopdateringer ("conda env update --file ...").
Fastlåsningen sker for at undgå at opdateringer på conda-forge fører
til inkompatibilitet med den primære FIRE-kildekode. Dette har i
praksis vist sig at være et problem.
Da der alligevel indføres ændringer i de fleste linjer i miljødefi-
nitionsfilerne "environment.yml" og "environment-dev.yml" er lejlig-
heden også benyttet til at reorganisere linjerne, så alle afhængig-
heder oplistes i alfabetisk orden. Det gør det blandt andet noget
lettere at sammenligne de to miljødefinitioner.
Resolves #290, #291
=> Fastlås pakkeversioner i condamiljøer

fire/api/_firedb_indset.py
Gør det muligt at lave indsættelser i databasen uden at committe dem. Det er praktisk fordi man da kan validere at data er konsistente inden det for alvor lægges i databasen, samt give en ekstra mulighed for at afbryde sessionen inden data indsættes for alvor. Eksempelvis:
```python
...
punkt = Punkt(...)
sagsevent = Sagsevent(punkter=[punkt], ...)
firedb.indset_sagsevent(sagsevent, commit=False)
try:
firedb.session.flush()
except:
firedb.session.rollback()
else:
if input("Du er ved at indsætte n punkter i databasen - er du sikker? ja/nej") == "ja":
firedb.session.commit()
else:
firedb.session.rollback()
```
=> Gør det muligt at undlade commits til databasen ved brug af indset-funktioner

fire/cli/niv/__init__.py, fire/cli/niv/opret_sag.py
Tilpasset hjælpeteksten i opret_sag, så den passer med virkeligheden, og rettet regnearksoprettelsen, så nyskrevet regneark åbnes for manuel  kontrol.
Resolves #297
=> tilpas opret sag, så hjælpetekst er korrekt, og nyskrevet regneark åbnes for manuel kontrol

.circleci/fire.ini, docs/installation.rst, fire/api/firedb.py, fire/cli/__init__.py, fire/cli/gama.py, fire/cli/info.py, fire/cli/niv/__init__.py, fire/cli/niv/ilæg_nye_koter.py, fire/cli/niv/ilæg_nye_punkter.py, fire/cli/niv/ilæg_observationer.py, fire/cli/niv/ilæg_revision.py, fire/cli/niv/læs_observationer.py, fire/cli/niv/netoversigt.py, fire/cli/niv/opret_sag.py, fire/cli/niv/regn.py, fire/cli/niv/udtræk_revision.py, fire/cli/søg/punkt.py, test/conftest.py
Her indføres flere ting:
1. prod, test og ci databaseforbindelser i `fire.ini` 
2. mulighed for at sætte en standarddatabaseforbindelse
3. mulighed for at angive schema i `fire.ini` frem for at hardcode. Hvis ikke sat i `fire.ini` faldes tilbage på `fire_adm` skemaet.
4. `--db` option tilføjet kommandolinjeværktøjer. Uden `--db` bruges standarddatabaseforbindelsen (alternativt prod), ellers vælges database med `--db=test` eller `--db=prod`.
Se commit messages for yderligere information.
=> Tillad valg af database på kommandolinjen

fire/api/firedb.py, fire/cli/niv/__init__.py, fire/cli/niv/opret_sag.py
Version og database skrives som parametre i projektfil. Eksempler i `fire niv --help` fremhæves med grøn, med henblik på at gøre livet nemmere for målerne der gerne vil kopiere eksempler og rette dem til fremfor at skrive kommandoerne selv:
=> Bitsandbobs

fire/api/_firedb_luk.py, fire/cli/__init__.py, fire/cli/niv/__init__.py, fire/cli/niv/luk_sag.py
Tilføjer en manglende brik:
```
$ fire niv luk-sag --help
Usage: fire niv luk-sag [OPTIONS] PROJEKTNAVN
Luk sag i databasen
Options:
--db [prod|test]  Vælg en specifik databaseforbindelse - default_connection
i fire.ini bruges hvis intet vælges.
-m, --monokrom    Vis ikke farver i terminalen
--debug           Vis debug output
--help            Vis denne hjælp tekst
```
=> fire niv luk-sag

fire/cli/niv/luk_sag.py
Både når database parameteren mangler og som feedback når sagen er
lukket eller lukning mislykkes.
=> fire niv luk-sag: Bedre output til brugeren

fire/api/firedb.py, fire/cli/niv/__init__.py, fire/cli/niv/ilæg_nye_punkter.py
Hovedformålet er at tage `firedb.tilknyt_landsnumre()` i brug, men derudover
indføres også en mere robust indsættelse af data og en ny metode til at
lade brugeren tage stilling til indsættelse eller ej.
Data indsættes nu i databasen løbende med henblik på at lade databasen
afsløre eventuelle fejlbehæftede data. Først allersidst, efter
brugerbekræftelse, committes til databasen. Herved sikres at data
indsættes korrekt ved afslutning af programmet.
Programparametrene `--alvor` og `--test` er fjernet, da det med `--db` nu er
muligt at specificere om man vil indsætte i test eller prod database.
Desuden er en ny bekræftelsesprompt indført, der spørger brugeren om hen
er sikker på at n punkter skal indsættes i [test|prod]-databasen. For at
indsætte data skal der svares "ja" to gange. Dette …
=> Refaktorering af 'fire niv ilæg-nye-punkter'

fire/cli/niv/_udtræk_revision.py
Løser nedenstående fejl
```
(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\test_udtræk>fire niv opret-sag 2021_revision "Revi 123-09 123-11 123-12"
Sags/projekt-navn: 2021_revision  (cb3674c9-dd3e-4992-a24c-e99892eadd2a)
Sagsbehandler:     B012858
Beskrivelse:       Revi 123-09 123-11 123-12
Opretter ny sag i test-databasen - er du sikker?  (ja/NEJ):
ja
Gentag svar for at bekræfte (ja/NEJ)
ja
Sag '2021_revision' oprettet
Skriver sagsregneark '2021_revision.xlsx'
Filen '2021_revision.xlsx' findes ikke.
Skriver: {'Sagsgang', 'Filoversigt', 'Nyetablerede punkter', 'Notater', 'Projektforside', 'Parametre'}
Til filen '2021_revision.xlsx'
Færdig! - åbner regneark for check.
(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\test_udtræk>fire niv udtræk-revision 2021_revision 123-11 123-12 123-09
Punkt: …
```
=> Undgå brug af uinitialiseret variabel 'datumstabilt'

fire/cli/niv/_regn.py
I funktionen 'spredning' var centreringsvariansen, frem for
centreringsspredningen, anvendt til beregning af den totale
spredning. Dette er nu korrigeret, så det er to spredninger,
der summeres til en samlet spredning med brug af hypot().
Samtidig er GNU Gama parameteren 'sigma-act' rettet fra
sigma-act='apriori' til
sigma-act='aposteriori'.
I testberegninger er den samlede effekt lille: Sprednings-
estimatet stiger med ca. 10%, mens koterne udviser ændringer
på mikrometerniveau.
Resolves #355
=> Korriger beregningsstatistikelementer

HOWTORELEASE.md
Absolut minimal beskrivelse, som sandsynligvis kan fjernes igen hvis vi indfører håndtering via CI.
Resolves #304
=> Beskriv afhængighedsopdatering i HOWTORELEASE

fire/cli/niv/_netoversigt.py, fire/cli/niv/_regn.py
Der er flere ting der kommer i røven af hinanden. Lang udredning herunder, primært for at jeg selv kan finde hoved og hale i det hele. Der kommer et par spørgsmål til sidst :-)
Fejlen manifesterer sig først og fremmest ved at Gama ikke producerer en output fil når man forsøger at lave en beregning på flere subnet på en gang, hvor der kun er et enkelt fastholdt punkt fordelt på de *n* subnet. Se herunder:
```
>fire niv regn 2018_KDI_RIKO
Så regner vi
Analyserer net
Fastholder 1 og beregner nye koter for 186 punkter
Check 2018_KDI_RIKO-resultat-kontrol.html
Traceback (most recent call last):
File "C:\Users\b012349\AppData\Local\Continuum\miniconda3\envs\fire-dev\Scripts\fire-script.py", line 33, in <module>
sys.exit(load_entry_point('fire', 'console_scripts', 'fire')())
File …
```
=> Håndter beregning af projekt mere end et nivellementsnet

fire/api/model/punkttyper.py, fire/cli/niv/_læs_observationer.py
Observationer til tabte punkter indlæses ikke. Ved læsning af observationer til tabt punkt gives advarsel som set herunder:
Hvis observationen skulle have været til et andet punkt er det nødvendigt at rette punktnummeret i observationsfilen.
=> fire niv læs-obs: Undgå læsning af obs til tabtgået punkt

fire/api/model/__init__.py, fire/api/model/sagstyper.py, fire/cli/niv/_luk_sag.py, sql/ddl.sql, test/sql/testdata.sql, test/test_firedb.py, test/test_ident.py, test/test_observation.py, test/test_sag.py
Ændrer DDL så sagsmateriale gemmes som BLOB fremfor en sti til et netværksdrev. `fire niv luk-sag` gemmer nu sagsmateriale i databasen.
Testdatabasen opdateres umiddelbart efter dette PR er merged. Venter nok lige en dags tid med at gøre det samme på produktionsdatabasen selvom det i dette tilfælde skulle være ganske ufarligt (den ændrede tabel bruges ikke i UM-mapping).
=> Sagsmateriale

fire/cli/niv/_ilæg_nye_punkter.py, test/sql/testdata.sql
I fire niv ilæg-nye-punkter fejlede koden ved indsættelse af
afmærkningspunktinfo, da afmærkningner af typen AFM:xxxx kræver at
tekstfeltet er udfyldt. Dette tages hånd om ved at bruge teksten fra
afmærkningscellen i regnearket.
Fejlen opstår da insert trigger på tabellen kontrollerer at det indsatte
er i overenstemmelse med den indsatte infotype. Under test er denne fejl
ikke opstået da triggeren PUNKTINFO_BIU_TRG fejlagtigt har været slået fra.
=> Undgå fejl ved indsættelse af afmærkning

fire/api/model/punkttyper.py, fire/cli/niv/_udtræk_revision.py
Punkt tilføjes landsnummer-property og implementerer nu __lt__ og __eq__
med henblik på at kunne sortere en liste af punkter. Punkterne sorteres
leksikografisk på deres landsnumre. Denne sortering sikrer en geografisk
gruppering af punkterne, også selvom punkternes har GI- eller GNSS-
identer.
Closes #368
=> Sorter punkter efter landsnummer i revisionsudtræk

fire/cli/niv/__init__.py
Påpeget af @ReneTandsbjerg. Eksempel på brug af `fire niv ilæg-revision` tilføjet og kommentar om ikke-funktionelle revisionsprogrammer fjernet.
=> Opdater helptext til fire niv

fire/cli/niv/__init__.py
Vi benytter ikke længere PROJEKTNAVN-resultat-filer,
så undlad at spørge om man har glemt at kopiere derfra
=> Udelad misvisende oplysning

fire/cli/niv/_læs_observationer.py
Kontroller at alle målinger på en given strækning er tildelt samme
hovedjournalsidenummer. Advar hvis dette ikke er tilfældet.
Kontroller at der er returmålinger for alle strækninger. Advar hvis
dette ikke er tilfældet.
Tilføj information om antallet af målinger på en given strækning i
"observationer.geojson".
Resolves #366
=> Bedre kontrol og formidling af returmålinger

scripts/load_shapefile.py
Kun relevant i forbindelse med initialisering af database til testsuiten.
=> Brug CI databaseforbindelse ved indlæsning af opmålingsdistrikter

docs/index.rst, docs/installation.rst, docs/konfiguration.rst
Efter afsnittet om konfigurationsfilen blev udskilt til egen fil
forsvandt den fra indholdsfortegnelsen pga manglende henvisning i
index.rst. Dette samt manglende labels er fikset. Derudover er
læseflowet optimeret så man kan nøjes med at læse
installationsvejledningen.
CC @larsnaesbye
=> Doc: Reparer installationsvejledning+konfigurationsfil

fire/cli/niv/_ilæg_observationer.py
Med #382 er en del drops blevet uaktuelle. De resterende var uaktuelle allerede.
Resolves #421
=> Drop uaktuelle drops fra ilæg-observationer

fire/cli/niv/_regn.py
Opløft og tidsforskel regnes nu med samme fortegn, så raten (i mm/år) får samme fortegn som opløftningen (i mm)
Resolves #419
=> Korriger fortegn for opløftrate

fire/api/model/punkttyper.py
`punkt._identer` udtrækkes fra punktets tilhørende punktinformationer, men udelader
punktinformationens `registreringtil`-information, så `punkt.ident` returnerer den
højest rangerende ident uden skelen til om den er aktuel eller ej.
Da `@property ident` er beregnet til identifikation af punktet i en primært
menneskelæsbar sammenhæng er det nok mest fornuftigt at udelade uaktuelle
identer. I tilfælde hvor "uaktuelle er aktuelle" vil vi formodentlig alligevel iterere
over alle punktinfø og dermed have adgang til `registreringfra/til`.
=> Udelad uaktuelle identer fra punkt._identer

fire/cli/niv/_udtræk_revision.py
Naturlige fikspunkter bliver udstillet på Valdemar og bør derfor
tages i betragtning i forbindelse med punktrevision.
Closes #434
=> Medtag naturlige fikspunkter i revisionsudtræk

fire/cli/niv/__init__.py
Ved normalisering af lokationskoordinat kontrolleres at
koordinaten befinder sig inden for dansk område. Hvis ikke det er
tilfældet smides en exception.
Løser problem med manglende oprettelse af nye punkter hvor koordinaten ikke er korrekt indtastet.
=> Fejl ved ikke-gyldig dansk lokationskoordinat

fire/api/firedb.py, fire/cli/niv/_udtræk_revision.py
Indfør garanti for at outputlisten matcher inputlisterne. Før dette
commit var der risiko for at outputlisten blev genereret i en
anden rækkefølge end inputlisterne, hvilket resulterede i fejl
når de to blev matched op mod hinanden, fx i `fire niv ilæg-nye-punkter`.
=>  tilknyt_landsnumre(): sikr at input- og outputlister matcher 

fire/cli/niv/_ilæg_nye_punkter.py, fire/cli/niv/_udtræk_revision.py, test/sql/testdata.sql
GI-punkter får et ATTR:GI_punkt, MV-punkter får et ATTR:MV_punkt
(mest for fuldstændighedens skyld), højdefikspunkter får et ATTR:højdefikspunkt
og vandstandsbrætter får et ATTR:vandstandsmåler
=> Tilknyt ATTR:-punktinfo til nyoprettede punkter

.pre-commit-config.yaml, docs/for_udviklere.rst, environment-dev.yml
Afvikler `black` i forbindelse med git commits:
```
(fire-dev) C:\dev\fire>git commit -m dummy
black....................................................................Failed
- hook id: black
- files were modified by this hook
reformatted fire\api\firedb.py
All done! \u2728 \U0001f370 \u2728
1 file reformatted.
```
Bemærk at der kan opstå fejl pga SIT's besynderlige valg af `%HOME%` på `H:\`:
```
(fire-dev) C:\dev\fire>git commit -m dummy
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to H:\patch1632218406-17172.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from …
```
=> Tilføj black pre-commit hook

fire/cli/niv/_ilæg_nye_punkter.py
Når der er tomme linjer i fanebladet giver det index fejl når der
itereres over range(n), hvorfor der i stedet itereres over dataframens
index. Index frasorterer automatisk blanke linjer og er dermed mere
robust. Her skal det dog bemærkes at felter med "usynlige" tegn som
mellemrum IKKE resulterer i en tom linje og en sådan vil fremtvinge
en fejl pga ugyldigt input.
closes #495
=> bugfix: ignorer tomme linjer i fire niv ilæg-nye-punkter

docs/workshop/workshop.rst, fire/cli/niv/__init__.py, fire/cli/niv/_læs_observationer.py, fire/cli/niv/_regn.py
Skæln mellem kontrolberegning og endelig beregning i geojson-output.
Situationen før og efter dette commit ved kørsel af udvalgte niv
kommandoer:
* `fire niv læs-observationer`:
- før og efter: `projekt-observationer.geojson` OG `projekt-punkter.geojson` oprettes 
* `fire niv regn` (første gang):
- før: `projekt-punkter.geojson` overskrives med information fra kontrolberegning (koter, fastholdt osv)
- efter: `projekt-kon-punkter.geojson` oprettes med information fra kontrolberegning
* `fire niv regn` (anden gang):
- før: `projekt-punkter.geojson` overskrives *igen* med ny information, denne gang fra endelig beregning.
- efter: `projekt-punkter.geojson` og `projekt-observationer.geojson` overskrives *igen* med ny information, denne gang fra endelig beregning.
Derudover er tilføjet en …
=> feat: separate geojson-filer for kontrol og endelig beregning

fire/api/configuration.py
funktionen `lambda: HOME / "." + RC_NAME` giver nedenstående fejl
når en `.fire.ini` bruges på Windows:
```
File "c:\dev\fire\fire\cli\__init__.py", line 10, in <module>
firedb = FireDb()
File "c:\dev\fire\fire\api\firedb\base.py", line 70, in __init__
self.config = get_configuration()
File "c:\dev\fire\fire\api\configuration.py", line 60, in get_configuration
parser.read(get_config_path())
File "c:\dev\fire\fire\api\configuration.py", line 49, in get_config_path
fname = get_fname()
File "c:\dev\fire\fire\api\configuration.py", line 16, in <lambda>
lambda: HOME / "." + RC_NAME,
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
```
Fikses ved at indsætte et par paranteser:
`lambda: HOME / ("." + RC_NAME)`
=> bugfix: Undgå fejl ved brug af .fire.ini på Windows

fire/cli/niv/_udtræk_revision.py
Det hænder at opmålingsdistrikterne ikke er digitaliseret korrekt og
enkelte punkter fejlagtigt ikke medtages i revisionsudtrækket. Det
forsøges forhindret ved at søge i et udvidet opmålingsdistrikt (
buffer på 50 m).
Closes #473
=> niv udtræk-revision: Tilføj buffer ved søgning i opmålingsdistrikt

test/sql/testdata.sql
Derudover er 
```
UPDATE punktinfotype SET beskrivelse = 'GNSS Stationsnummer' WHERE infotype = 'IDENT:GNSS';
COMMIT;
```
kørt på både test- og produktionsdatabaserne.
Closes #501
=> Ret GNNS til GNSS i testdatasæt

fire/api/firedb/__init__.py
Grundet manglende ^ i regex fremsøges løbenumre for distriktet 29-06
både blandt landsnumre der starter med 29-06 *OG* 129-06. Hvilket
resulterer i at løbenumre i 29-06 springes over hvis de er optagede i
129-06. Rettet i dette commit.
=> bugfix: undgå at tilknyt_landsnr() tildeler ikke-sekventielle løbenumre

fire/cli/niv/_udtræk_revision.py
Fra tid til anden er det praktisk at kunne trække ALLE punktinfo
ud i forbindelse med punktrevision. --alle-attributter nulstiller
listen med ellers ignorerede punktinfo og trækker alle punktets
attributter ud.
=> fire niv udtræk-revision: Tilføj --alle-attributter

fire/api/model/__init__.py, fire/enumtools.py, test/conftest.py, test/test_enumtools.py
Sandsynligvis forårsaget af opdateringen af SQLAlchemy, havde BetterBehavedEnum nu brug for en validering af inputværdien, den skaber en enum-værdi ud fra, hvor den ikke var nødvendig før.
Valideringen foregår ved at se, om den ønskede værdi kan repræsenteres af den pågældende enum-klasse (nedarvet fra betterBehavedEnum). Kan den ikke dette, returnerer metoden, hvilket vil sige, den sender værdien `None` tilbage til den kaldende funktionalitet.
=> Check om værdi findes i enum.

fire/matematik.py, test/test_matematik.py
Indeholder indtil videre funktioner til konvertering mellem geocentriske og topocentriske koordinatforskelle.
Som test (udover de formelle til test-suiten) har jeg lavet nogle forskellige forsøg med data fra ADDNEQ2. Nedenstående script beregner for BUDP rotationsmatrix (NEU->XYZ), NEU covariansmatrix (roteret XYZ covarians), spredninger fra de to covariansmatricer samt en ny XYZ-covariansmatrix baseret på NEU-spredninger fra ADDNEQ-filen. Se output helt i bunden.
Jeg er i tvivl om det hele stemmer. Den XYZ-covariansmatrix jeg beregner ud fra de empiriske NEU-spredninger er en størrelsesorden eller to større end hvad der findes i COV-filen. Om det skyldes fejl fra min side eller om det simpelthen bare er varianserne der bliver større når de er bestemt empirisk kontra når de beregnes (??) …
=> Tilføjelse af matematikmodul

fire/io/bernese.py, test/test_bernese.py
I forbindelse med #549 er jeg stødt på nogle uhensigtsmæssige konstruktioner i `BerneseSolution`. De rettes i dette PR for at lette det videre arbejde. Overordnet set ændres
1. Spredninger læses for alle tre koordinatkomponenter
2. Kovarianser fra COV-filen skaleres med RMS unit of weight
3. Sprogbruget vedr. koordinatresidualer på dagsløsningerne præciseres
4. Kovariansmatrix beregnes for dagsløsningernes koordinatresidualer
5. `BerneseSoultion.a_posteriori_RMS` fjernes da samme værdi aflæses fra COV-filen i forbindelse med skalering af kovariansmatricer
=> Diverse forbedringer til BerneseSolution

fire/cli/niv/_læs_observationer.py
Når nye punkter endnu ikke er oprettet kan `fire niv læs-observationer`
ikke udtrække landsnumrene, hvorfor de foreløbige navne skal bruges.
Det forventes at `set_index()` smider en exception ved duplerede
værdier i en kolonne (eksempelvis to tommer celler), men den antagelser
holder ikke (længere?). Denne adfærd sikres ved tilføjelse af
`verify_integrity=True` til kaldet.
Herefter udstedes advarsel som forventet til brugeren:
```
Der mangler landsnumre til nyetablerede punkter.
Har du husket at lægge dem i databasen?
Fortsætter beregningen med brug af de foreløbige navne
Importerer observationer
```
Fixes #573
=> Bugfix: Brug foreløbige navne når landsnumre ikke oprettet

fire/api/model/columntypes.py, fire/api/model/geometry.py, test/gama/test_gama_read.py, test/gama/test_gama_write.py, tox.ini
Pytest konfigureret, via `tox.ini`, til at fejle når en `*Warning` udstedes i koden. Der udstedes en del advarsler af SQLAlchemy i forbindelse med forberedelse til v. 2.0. Dem har vi hidtil overset. Med denne ændring skulle det gerne være meget tydeligt når en ny advarsel dukker op (= testsuiten fejler).
Alle eksisterende advarsler er taget hånd om. Primært handler de om SQLAlchemy, men enkelte forbedringer er også lavet i tests af `fire.gama` og en `DeprecationWarning` fra `pytest_freezegun` ignoreres. Sidstnævnte forsøges håndteret opstrøms men projektet ser ud til at være halvdødt, hvorfor jeg har forsøgt mig med at tilføje en patch i conda-forge pakken.  Forhåbentligt bliver sidstnævnte accepteret.
Tagget som milestone 1.4, da det er relevant at nævne at diverse SQLAlchemy advarsler …
=> pytest: Fejl når advarsler udstedes

fire/cli/niv/_ilæg_nye_punkter.py
Undgå at AFM:2700 og lign. indsættes som tekstfelt i punktinformationer
for nyoprettede punkter. Vi tillader at brugeren skriver AFM:2700 som
afmærkningstype i regnearket men fører det ikke længere ukritisk videre
til databasen.
Løser første del af https://github.com/Kortforsyningen/FIRE/issues/563
=> Indsæt korrekt tekst ved oprettelse af AFM:nnnn punktinfo

fire/cli/niv/_ilæg_nye_punkter.py
`fire niv ilæg-nye-punkter` fejler hvis beskrivelsesfeltet ikke er
udfyldt. Hermed undgår vi at der udstilles punkter uden beskrivelse
på Valdemar.
Hvis på punktoprettelsestidspunktet ikke er muligt at skrive den fulde
beskrivelse må en kort, midlertidig, tekst skrives og uddybes på et
senere tidspunkt.
Closes #561
=> Påkræv beskrivelse ved nyoprettelse af punkter

fire/api/firedb/__init__.py, fire/api/firedb/base.py, fire/api/model/__init__.py, sql/ddl.sql, test/sql/testdata.sql, test/test_firedb.py
Med indførelse af grafik-tabellen, og tilhørende kode, er Konfigurations
-tabel og -klasse blevet overflødig og kan betragtes som et fejlslået
eksperiment.
Closes #545
**Bemærk**: Ikke relevant at inkludere i release-notes til brugere
=> Fjern Konfiguration

fire/cli/niv/_ilæg_observationer.py
Fremadrettet betyder det at ikke er nødvendigt at redigere direkte i observationsfilen. Ændringer i de indlæste observationer kan laves direkte i regnearket. Observationer med x i "Sluk"-kolonnen lægges ikke i databasen når `fire niv ilæg-observationer` køres.
Closes #548
=> Undlad at indlæse slukkede observationer i databasen

fire/cli/niv/_ilæg_nye_punkter.py
Tidligere er variationer af fx "bolt" ved opdatering af regneark
blevet omskrevet til "AFM:2700 - Bolt". Det har to ulemper:
1. Det gør det svært at debugge fejl
2. Det træner brugerne til at tro det er måden afmærningstypen angives på
Relateret til #578
=> niv ilæg-nye-punkter: undlad at omskrive tekst i afmærkningsfelt

fire/io/regneark/__init__.py
Det er tilsyneladende ikke muligt at åbne et regneark i appen-mode med
`xlsxwriter`, derfor bruges i stedet `openpyxl`.
Closes #585
=> Brug openpyxl engine til opdatering af regneark

fire/cli/info.py
Tidligere lavedes et for simpelt tjek af om talværdien af et punktinfo
er sat eller ej. I tilfældet hvor talværdien er 0.0 vil `info.tal or ""`
resultere i den tomme streng da 0.0 evaluerer False. Tages hånd om ved
et mere eksplicit tjek af variables indhold
=> info punkt: Sikr at punkinfos talværdi skrives hvis den er 0.0

fire/cli/niv/_ilæg_revision.py
Ved revision af lokationskoordinater bruges den eksisterende koordinat
til en rudimentær kontrol af fejlindlæsning af nye koordinater. Når et
punkt mangler en lokationskoordinat fejler læsningen og programmet
afbrydes. Dette commit tager hånd om dette og bruger koordinaten (11.0,
56.0) som den eksisterende lokationskoordinat. Dette er analogt til hvad
der skrives i revisionsregnearket ved udtræk.
=> Undgå fejl ved revision af lokationskoordinatløse punkter

fire/cli/info.py
Standardvisningen af information om et punkt ændres til kun at vise
aktuelt data. Tidligere versioner af punktinfo m.m. vises ved
tilføjelse af `-H` eller `--historik` i kald til `fire info punkt`.
Ændringen foretages da det efter lang tids brug er vurderet at de
historiske informationer støjer mere end de gavner i de fleste udtræk.
Closes #247
=> Tilføj --historik flag til fire info punkt

fire/cli/niv/_udtræk_revision.py
Ansporet af revisionsudtræk i Sønderjylland ændres funktionaliteten
sådan at punkter markeret med REGION:EE, REGION:FO, REGION:GL,
REGION:SE og REGION:SJ ikke trækkes ud i forbindelse med punktrevision.
Konkret betyder det ca. en faktor 10 færre udtrukne punkter i
sønderjyske opmålingsdistrikter, fx 1748 vs 174 i K-84.
=> Undgå punktrevision i andre regioner end DK

docs/konfiguration.rst, fire/api/configuration.py, fire/api/firedb/__init__.py, fire/cli/__init__.py, fire/cli/niv/_ilæg_revision.py, fire/cli/niv/_opret_sag.py, fire/cli/niv/_regn.py, fire/cli/niv/_udtræk_revision.py, flame/help/source/conf.py, scripts/load_shapefile.py, test/api/niv/test_ilæg_revision.py, test/conftest.py
Giver brugeren mulighed for at undgå at regneark åbnes automatisk
efter endt `fire niv` kommando. Formentligt primært anvendeligt
for udviklere. Det er da også netop forbedret udvikling der er
anledning til dette commit: Afvikling af test-suiten på Windows
fejler når regneark åbnes af `fire niv xxx`. Derfor slås åbning af
filerne fra i test-suitens instans af FireDb.
=> Gør åbning af filer med fire niv konfigurerbar

fire/api/firedb/__init__.py, fire/api/firedb/indset.py, fire/api/model/sagstyper.py, fire/cli/grafik/__init__.py, fire/cli/niv/_ilæg_nye_koter.py, fire/cli/niv/_ilæg_revision.py, fire/cli/niv/_luk_sag.py, test/conftest.py, test/niv/test_niv.py, test/test_sag.py
Tilføjer to "genveje" til nemmere håndtering af sager og sagsevents. En sag kan nu oprettes uden at skulle bakse med `Sagsinfo` og andet "fyld":
```python
sag = firedb.ny_sag(
behandler=sagsbehandler,
beskrivelse="Indsættelse af ny grafik med 'fire grafik'",
)
```
som står i kontrast til den tidligere måde at oprette en sag på:
```python
sag = Sag(
id=fire.uuid(),
sagsinfos=[
Sagsinfo(
aktiv="true",
behandler=sagsbehandler,
beskrivelse="Indsættelse af ny grafik med 'fire grafik'",
)
]
```
Tilsvarende er oprettelse af sagsevents forsimplet:
```python
sagsevent = sag.ny_sagsevent(
beskrivelse=f"Sagsmateriale for {projektnavn}",
materialer=[zipped.getvalue()],
)
```
hvor man tidligere har skulle folde det hele mere ud:
```python
sagsevent = Sagsevent(
sag=sag,
eventtype=EventType.KOMMENTAR, …
```
=> Simplificer sags(event)oprettelse

scripts/reset-test-db.sh, sql/sweep_db.sql
Særdeles nyttigt når der under udvikling ændres på DDL eller test- databasens indhold. Gør det muligt at nulstille tabellerne uden at skulle gentarte hele databasen. Sparer en del tid.
=> Tilføj script til genoprettelse af testdatabasens indhold

fire/cli/grafik/__init__.py, fire/cli/niv/_ilæg_revision.py
Enkelte steder er forkert funktionsnavn brugt eller manglende angivelse af parameternavn (beskrivelse).
Opfølgning på #628
=> Ret fejl i kald af Sag.ny_sagsevent

fire/cli/niv/__init__.py
Forskelle i patch-nummer ignoreres, da der ikke bør være forskel i funktionalitet mellem disse versioner.
Forskelle i minorversion resulterer i en advarsel hvis filens minorversion er større end den installerede version af FIRE, da der potentielt kan være ny funktionalitet i den højere version.
Forskelle i majorversion resulterer i en fejl og programmet afbrydes. Det må forventes at der er store ændringer i funktionalitet, der forhindrer bagudkompatibilitet. Det er et teoretisk anliggende på nuværende tidspunkt og bør tages op til overvejelse den dag en version 2 af FIRE skal i omløb.
Eksempler på adfærd ved forskelle i patch, minor og major numre.
Patch-version afviger fra installeret version. Ingen anmærkninger fra FIRE:
$ fire niv udtræk-revision flaf RDIO
Punkt: K-63-00909
Skriver: …
=> fire niv: Slæk versionsnummercheck ved læsning af sagsfiler

fire/api/firedb/hent.py, fire/api/niv/udtræk_observationer.py, fire/cli/niv/_udtræk_observationer.py, test/test_observation.py
Primær forskel er ændring i fremsøgningsmekanismen, hvor der som udgangspunkt nu kun findes observationer mellem de punkter der spørges efter. De gamle funktionalitet kan opnås ved at tilføje `--alle-obs`.
Derudover er nogle småting rettet, især deprecation warnings fra pandas.
=> Forbedringer af `fire niv udtræk-observationer`

fire/cli/ts/gnss.py
Der er for meget bøvl med Excels forståelser af indholdet af en ellers simpel CSV fil. For at undgå problemer med forkert tolkning af datatyper bruger vi i stedet bare Excels eget format - så går der ikke kludder i det.
=> Ændr csv eksport til export af Excel-filer

docs/installation.rst
Den tidligere formulering skabte forvirring, og der er ingen skade sket ved at holde conda miljøet opdateret (selv ved en patch opdatering)
=> Simplificer vejledning i opdatering af FIRE

fire/api/model/tidsserier.py, fire/matematik.py, test/test_matematik.py
To fejl identificeret og rettet:
1. Der var byttet om på længde- og breddegrad funktionskald til dannelse af rotationsmatrix
2. Rotationsmatrix forkert bygget op
Med disse fejl rettet ser de tre komponenter mere korrekte ud i tidsserieplots.
Herunder et sæt før og efter plots til visuel verifikation af ændringerne. Generelt ses en væsentligt pænere nord-komponent og større udsving på up-komponenten. Nord og up er ikke længere (tilsyneladende) korrelerede.
BUDP_5D_IGb08_før:
BUDP_5D_IGb08_efter
SMID_5D_IGb08_før
SMID_5D_IGb08_efter
HABY_5D_IGb08_før
HABY_5D_IGb08_efter
=> Ret fejl i NEU-tidsseriekomponenter

fire/api/model/punkttyper.py
Property Punkt.tabtgået manglede tjek for registreringtil hvilket resulterede i fejlagtige meldinger om tabtgåede punkter når fx `fire niv læs-observationer` afvikles.
=> Punkt: Rapporter kun som tabtgået hvis punktinfo er gyldig

fire/cli/niv/_opret_sag.py
I tilfælde hvor sag ikke oprettes i databasen (men regneark stadig genereres) er det i nuværende form nemt at overse at sagen ikke er oprettet i databasen. Med denne ændring laves advarselsteksten mere tydeligt, blandt andet ved at skrive den på en gul baggrund.
Før:
Efter:
=> niv opret-sag: Tydeligør at sag ikke oprettes i DB

fire/api/niv/udtræk_observationer.py, fire/cli/niv/_udtræk_observationer.py
Punktoversigten blev tidligere kun dannet ud fra opstillingspunkterne. I få tilfælde er der observationer hvor sigtepunktet ikke er brugt som opstillingspunkt, hvorfor punktoversigten blev ukomplet. Det er løst med dette commit.
Kontrol af punktoversigten er fjernet, da vi nu ved hjælp af set-operationer er garanteret at få den komplette liste.
Closes #694
=> Sikr at punktoversigt indeholder alle udtrukne observationspunkter

fire/api/firedb/indset.py, test/test_sag.py
Der er lidt cirkulær logik i samspillet mellem `FireDb.ny_sag` og `FireDb.indset_sag`. I førstnævnte er det fordelagtigt at den nyoprettede sag tilføjes den aktive session. Ligeledes er det praktisk/nødvendigt at `FireDb.indset_sat` sikrer sig at sagen er tilføjet sessionen. Nu gøres det uden at trigge en exception hvis sagen allerede er tilføjet.
Før dette fix fejler testen `test_indset_ny_sag`.
=> FireDb.indset_sag: Undlad exception hvis sag er tilføjet session

fire/cli/niv/__init__.py
Rækker i regnearket hvor punkter er fastholdte kan efter ændringer i numpy resulterer i at "Ny kote" indeholder NaN i stedet for None. Det resulterer i at alle punkter fremstår om ikke-fastholdte i geojson-outputtet. Ligeledes er alle talværdier i rækkerne sat til nan, hvilket ikke er korrekt.
Dette tages der nu højde for i punkt_feature() hvor der er indført et check for nan.
skriv_punkter_geojson() er også i brug i forbindelse med læsning af observationer, og der genereres input til funktionen lidt anderledes. Derfor er checkes der stadig for None. Det står i skrivende stund uklart om det stadig er aktuelt, men vi beholder både livrem og seler på for en sikkerheds skyld.
=> Håndter fastholdte punkter korrekt i geojson-filer i forbindelse med beregning

fire/api/model/geometry.py
Fiona har ændret adfærd i forbindelse med en opdatering og returnerer nu sine egne objekter, frem for "bare" en dict. Funktionaliteten er den samme og en fiona geometry nedarver tilsyneladende fra en dict.
Eksisterende læsning af geometry fra dict bibeholdt for en sikkerheds skyld. Der kan sagtens være forskellige fiona versioner i brug på brugernes maskiner - ingen grund til at det resulterer i fejl.
=> Tilføj mulighed for at oprette Geometry fra fiona objekt

docs/apps/luk.rst, fire/api/firedb/__init__.py, fire/cli/info.py, fire/cli/luk.py, test/test_koordinat.py
Tilpasning af `FireDb.fejlmeld_koordinat()` så den virker i alle mulige scenarier. Ny CLI funktion `fire luk koordinat` tilføjet for at kunne lukke/fejlmelde koordinater der er forkert eller fejlindsatte. En lille konsekvensrettelser i `fire info punkt` gør at disse fejlmeldte koordinater for et "X" som markør i outputtet fra funktionen (se eksempel i commit messages).
=> Fejlmelding af koordinater

environment-dev.yml, environment.yml
Pandas 2.2 er begyndt at smide en DeprecationWarning, der advarer om at pyarrow bliver en hård afhængighed fra pandas 3.0. For at lukke munden på pandas (og tillade at testsuiten afvikles) tilføjes pyarrow. Ligeledes opdateres enkelte pakker til nyere version.
=> Opdater mamba miljøer

.github/workflows/tests.yml, scripts/init-db.sh, sql/views.sql, test/ci/init.sql
Følgende views er tilføjet:
1. V_FIKSPUNKTER_DK
2. V_CORS_DK
3. V_TAPAS
4. V_5D_PUNKTER
5. V_10KM_PUNKTER
6. V_DMI_VANDSTANDSMAALERE
7. V_DVR90_VANDSTANDSMAALERE
8. V_GPSNET
9. V_SMARTNET
10. V_RTKCONNECT
11. V_TABTE_PUNKTER
12. V_GNET
13. V_PRES1_OBS
14. V_PRES2_OBS
15. V_PRES3_OBS
Alle views er konstrueret som "materialized views", da dette er den eneste måde at lave spatial index på et view i en Oracle database. Views er konstrueret sådan, at de opdateres en gang i timen for ikke at overbelaste databasen mere end højest nødvendigt. Dog med undtagelse af views med observationer fra de tre landsdækkende
præcisionsnivellementer, da disse ikke forventes at ændre sig over tid.
=> Tilføj database-views mhp brug i QGIS

sql/views.sql
Følgende ændringer foretaget:
1. IDENT:ekstern tilføjet som attribut på views over RTK-tjenesternes stationer
2. IDEN:GNSS sat som første attribut i lagene, så labels kan sættes nemt i QGIS (højreklik på lag, "vis labels")
3. Bounding boxes er tilpasset Danmark for alle views pånær det med GNET
=> Opdater views

fire/cli/niv/_ilæg_observationer.py
Vi kopierer ikke faneblad rundt mellem forskellige filer i det almindelige workflow. Det var en fiks ide i et tidligt stadie af udviklingen.
Closes #724
=> fire niv ilæg-observationer: Fjern overflødigt output fra tidlig prototype

fire/api/firedb/hent.py
`TS:jessen` kunne fx ikke findes, da der ikke var konsistens i brug af `upper()` i SQL-udtræk.
=> Sørg for at `fire info srid` kan finde alle SRID'er

fire/cli/niv/_netoversigt.py, test/api/niv/test_netanalyse.py
resolves #701
Commits 2d736f8 og 10a2678 tilføjer tests af eksisterende funktioner og skulle gerne virke for sig selv.
926b6e4 ændrer analyser_subnet så breadth first search anvendes i stedet for depth first. 
Derudover tilføjes path_exists, som var tænkt at skulle bruges i stedet for path_to_origin.
Imidlertid ændrer 37d4389 på netgraf-funktionen, så hverken den gamle path_to_origin eller den nye path_exists nogensinde bliver kaldt. Hvis det ønskes kan jeg godt fjerne begge to funktioner i et nyt commit, for at gøre det hele mere "clean". 
Mangler desuden test af path_exists, men hvis denne skal fjernes er test unødvendig.
=> Ændringer til netværksanalyse i fire niv

fire/ident.py, test/ident/test_ident_validering.py
resolves #760
Har ændret vandstandsbrætmønsteret, sådan at "v" med både stort og småt genkendes i mønstret.
Derudover tilføjet funktion reformater_vandstandsbræt som konverterer til ident upper case, og kald til denne i klargør_ident_til_søgning.
Tilsidst tilføjer denne PR også testfunktion af kan_være_vandstandsbræt, samt testcases for alle identer skrevet med småt.
=> Fix vandstandsbrætmønster og klargøring af ident til søgning

sql/views.sql
Formålet er, at kunne skælne mellem tjenestens egne stationer og vores stationer, fx på et kort.
=> SQL Views: Tilføj `IN_DKCORS` attribut til RTK-tjeneste net

fire/api/firedb/hent.py, fire/api/model/punkttyper.py, test/conftest.py, test/sql/testdata.sql, test/test_punktsamling.py
https://github.com/SDFIdk/FIRE/commit/661211aa3557551245639ccab5d273801d3a5cc3: Tilføjer ny metode til at hente alle punktsamlinger, samt test heraf. 
https://github.com/SDFIdk/FIRE/commit/df6b0a24b10bd5252b70e94b6ed1f1aa0c541e98: Tilføjer ny property på Punkt, som trækker punktets "IDENT:jessen" ud hvis det findes fra Punktinfo. Derudover mindre refaktorisering af lignende properties til lands- og gnss-nummer.
https://github.com/SDFIdk/FIRE/commit/d6f63c49f2df759b7dac5bbc44866b2beee6c042: Ændrer SQLAlchemy mapping mellem Punkt og Punktsamling. Indeholder ingen ændringer på database-niveau. Når man slår op på "Punkt.punktsamlinger" joines nu via tabellen Punktsamling_Punkt i stedet for at gå direkte via Punktsamling.Jessenpunkt.
Dvs at Punkt.punktsamlinger nu opfører sig på samme måde som …
=> API ændringer til Punktsamlinger

sql/views.sql
`V_FIKSPUNKTER` får en ny kolonne der angiver om fikspunktet er restricted eller ej. `V_CORS_DK` får en kolonne der angiver om det er en klasse A station eller ej. I begge tilfælde sættes feltet til `TRUE` hvis betingelsen er opfyldt, ellers efterlades det tomt.
=> Tilføjelser til views `V_FIKSPUNKTER` og `V_CORS_DK`

docs/datamodel.rst, fire/api/firedb/hent.py, fire/api/model/punkttyper.py, fire/api/model/tidsserier.py, fire/cli/indlæs/bernese.py, fire/cli/ts/gnss.py, sql/ddl.sql, test/api/tidsserier/test_analyse_af_tidsserier.py, test/conftest.py, test/sql/testdata.sql, test/test_srid.py, test/test_tidsserie.py
Skal bruges til diverse brugervendte formål  i stedet for Srid, i tilfælde hvor beskrivelses-feltet er upraktisk. Fx fremsøgning på DVR90, IGb08, Jessen i stedet for hhv. EPSG:5799, EPSG:9015, TS:Jessen,  eller generering af rapporter som vises i terminalen (fx viser fire info punkt et punkts koordinater med angivelse af sriden, hvilket oftest er EPSG-koden. Med denne ændring behøves man ikke at kunne alle EPSG-koderne i hovedet når man får vist en rapport som dén.) 
Derudover indeholder denne PR fjernelsen af feltet "referenceramme" på Tidsserie-tabellen, som tjente samme formål som det nye kortnavn og er derfor redundant. Dog beholdes attributten "referenceramme" i Tidsserie-api'et, der nu henter værdien fra srid.kortnavn 
Denne PR indholder ligesom #768 ændringer på DDL-niveau. Jeg har …
=> Tilføj kolonne "kortnavn" på sridtype

.github/workflows/tests.yml, fire/api/firedb/hent.py
De bliver sjældent brugt, og spænder jævnligt ben for opslag af jessennumre.
Closes #754
=> Udelad refgeo id'er fra søgning med FireDb.hent_punkt()

test/test_punktinformation.py
test_punktinformation indsætter et landsnummer i CI-databasen for et tilfældigt punkt, uden at rulle tilbage. Køres testen flere gange i træk, vil der ligge flere punkter i CI-databasen med samme landsnummer.
PR #768 opretter bl.a. triggeren punktinfo_bi_trg som netop sørger for at man ikke kan indsætte det samme GI-, lands- eller jessennr til forskellige punkter. Denne trigger aktiveres ved gentagne kørsler af ovenstående test.
Har omskrevet testene i test_punktinformation, så alle indsatte objekter, herunder landsnumre, rulles tilbage sidst i testen.
=> Fix fejl i test_punktinformation introduceret ved merge af #768

fire/cli/luk.py, fire/cli/niv/__init__.py, fire/cli/niv/_ilæg_nye_koter.py, fire/cli/niv/_ilæg_nye_punkter.py, fire/cli/niv/_ilæg_observationer.py, fire/cli/niv/_læs_observationer.py, fire/cli/niv/_opret_sag.py, fire/cli/niv/_regn.py, fire/cli/niv/_udtræk_observationer.py
Bemærk: Dette PR ligger oven på https://github.com/SDFIdk/FIRE/pull/775 og skal først derfor først merges efter https://github.com/SDFIdk/FIRE/pull/775 er blevet merget! Den første commit der skal tages stilling til er 90f2ffbe31b42692dc207d9bfce4dcf9de80579a. Commits før denne hører til andre pull requests.
Denne PR tilføjer resten af funktionaliteten i niv-modulet, nødvendig for at oprette, vedligeholde og slette Punktsamlinger og Højdetidsserier. Derudover indeholdes nogle generelle forbedringer for at gøre niv-modulet mere ensartet. 
Commitsne er inddelt som følger:
- 90f2ffb, 66acbfb og dbe14e6ecca03480652e8bf8e883e340d6271981 laver generelle forbedringer/ændringer til eksisterende kommandoer. 
- b09e859c06dfef0725a0186ec190023217d41277 giver mulighed for at lukke tidsserier og …
=> Punktsamling 4: Tilføj nye niv-underkommandoer til håndtering af punktsamlinger og tidsserie

docs/datamodel.rst, docs/tips/punktsamlinger.rst, docs/workshop/htscase.rst, fire/api/model/observationer.py, fire/cli/niv/_ilæg_nye_punkter.py, fire/cli/ts/hts.py
Forskellige småting opdaget under live demo. Herunder:
En enkelt billedfil er gemt som "regn_plot.png", men bliver i dokumentationen refereret som "regn_plot.PNG". Dette går fint når man bygger dokumentationen lokalt, men kan se at billedet ikke bliver vist når det bygges af github.
=> Ret stavefejl og andre småting i dokumentation

sql/views.sql
- V_TABTE_PUNKTER frasorterer ikke længere punkter uden beskrivelse eller landsnr (INNER JOIN -> LEFT JOIN)
- V_PRES1, 2 og 3 har fået tilføjet identer for opstillings- og sigtepunkter så disse kan bruges fx til labels QGIS.
=> Ret views til 1.-3. præc og tabte punkter

fire/io/regneark/__init__.py
Fixes #798
uuid skal svare til id'et for det sagseventid som lagde koten i kolonnen "ny kote"  i databasen. Dette sker først efter man har kørt fire niv ilæg-nye-koter
=> Fjern indsættelse af uuid i Punktoversigt ved udtræk af observationer

fire/api/niv/udtræk_observationer.py, fire/cli/niv/_udtræk_observationer.py, fire/io/regneark/__init__.py, test/api/niv/test_udtræk_observationer.py
Fixes #802
Føjer parameteren `--præc` / `-P` til `fire niv udtræk-observationer` så det er muligt at filtrere observationer på de tre præcisionsnivellementer.
=> Tilføj mulighed for at filtrere på præcisionsnivellement

environment-dev.yml, environment.yml, fire/cli/niv/_ilæg_revision.py
Ved oprettelse af nye punkter med `fire niv ilæg-revision` resulterer oprettelse af punkter udenfor Danmark i en fejl før denne ændring. Fejlen opstår fordi det forventes at punktet er indeholdt i et opmålingsdristrikt. Når punktet ikke er det går det galt. Derfor frasorteres punkter udenfor Danmark nu før der tildeles landsnumre.
Som nævnt i en kommentar i koden er det et rudimentært tjek, der på sigt kan forfines. For nu bør det løse problemet i lang de fleste tilfælde.
`shapely` er eksplicit tilføjet mamba-miljøet. Pakken er i forvejen tilgængelig, da den benyttes af andre pakker og er derfor ikke en ny afhængighed som sådan.
Herunder ses de to polygoner der bruges til at afgøre om et punkt befinder sig indenfor Danmark eller ej. Med grønt er vist opmålingsdistrikterne og gråt giver …
=> Undlad oprettelse af landsnumre for punkter udenfor DK

fire/cli/niv/__init__.py
Der blev anvendt `firedb`, hvilket svarer til default-databaseforbindelsen. Dette er rettet til `fire.cli.firedb`, således at der nu anvendes forbindelsen valgt med `--db` parameteren
Fixes #816
=> Anvend korrekt database i funktionen udled_jessenpunkt_fra_punktoversigt

fire/cli/niv/_ilæg_revision.py
Det præciseres at både tekst- og talattributter skal opdateres ved brug af kolonnen "Ny værdi" i regnearket. Der har været forvirring om det hos flere af målerne.
=> fire niv ilæg-revision: Præciser dokumentation

fire/api/firedb/hent.py, fire/api/model/sagstyper.py, fire/cli/info.py
En lille udvidelse som jeg kom til at lave. Gør så man med fire info sag kan lave fritekstsøgning  på sags-beskrivelsen og filtrere sager på registreringfra-datoen. Hvis søgningen giver flere resultater, så vises en liste af sager (på samme måde som før, hvis man ikke gav noget input), og hvis søgning giver ét resultat vises detaljer om sagen.
Flere resultater:
```
>fire info sag KDI -df 25-04-2024 -dt 25-06-2024
Sagsid     Behandler           Beskrivelse
---------  ------------------  -----------
c326e995:  B363493             KDI: vand sag til tilføj KDI vandsstandsmåler...
48866e21:  b004276             2024_KDI_KLOSTER:...
```
Ét resultat:
```
>fire info sag KDI_KLOSTER
------------------------- SAG -------------------------
Sagsid        : 48866e21-6409-42db-b7ea-d7b8b8f71826 …
```
=> Udvid fire info sag med mere fleksibel søgefunktionalitet

fire/api/firedb/hent.py, test/sql/testdata.sql, test/test_punkt.py
Vi er begyndt at registrere GNSS-stationer med deres fulde ID. Det er praktisk da det fjerner tvetydighed i nogle tilfælde, men gør fremsøgning af punkter lidt mere bøvlet. Med denne ændring kan man finde "KULU00GRL" ved at søge på "KULU" med fx `fire info punkt`.
=> FireDb.hent_punkter: Find 9-tegns GNSS ident fra første 4 tegn

sql/views.sql
Viewet er allerede opdateret i prod og test.
=> Ret v_alle_niv_obs: undgå dublering af observationer pga multiple sagseventinfos
